// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif
#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// --------------- //
// otis_pseudo_pps //
// --------------- //

#define otis_pseudo_pps_wrap_target 0
#define otis_pseudo_pps_wrap 12
#define otis_pseudo_pps_pio_version 0

static __pio_const uint16_t otis_pseudo_pps_program_instructions[] = {
            //     .wrap_target
    0xe000, //  0: set    pins, 0
    0x80a0, //  1: pull   block
    0x6040, //  2: out    y, 32
    0x006a, //  3: jmp    !y, 10
    0x80a0, //  4: pull   block
    0x6020, //  5: out    x, 32
    0x0046, //  6: jmp    x--, 6
    0xe001, //  7: set    pins, 1
    0x0088, //  8: jmp    y--, 8
    0x0000, //  9: jmp    0
    0xe000, // 10: set    pins, 0
    0xc007, // 11: irq    nowait 7
    0x000c, // 12: jmp    12
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program otis_pseudo_pps_program = {
    .instructions = otis_pseudo_pps_program_instructions,
    .length = 13,
    .origin = -1,
    .pio_version = otis_pseudo_pps_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config otis_pseudo_pps_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + otis_pseudo_pps_wrap_target, offset + otis_pseudo_pps_wrap);
    return c;
}
#endif
