// Generated from data_contracts/otis_firmware_host_contract_v1.json.
// Do not edit by hand; run tools/generate_firmware_host_contract.py.
#ifndef OTIS_FIRMWARE_HOST_CONTRACT_GENERATED_H
#define OTIS_FIRMWARE_HOST_CONTRACT_GENERATED_H

#define OTIS_FIRMWARE_HOST_CONTRACT_ID "OTIS_FIRMWARE_HOST_CONTRACT_V2"
#define OTIS_FIRMWARE_HOST_CONTRACT_SHA256 "d29f12260ef4ed68e0272a5a38ba1637046d28e62fe6aa97b1f97a2c6ae2711c"

#define OTIS_CONTRACT_ACCEPTED_PPS_SPANS_V1_HEADER "record_type,schema_version,capture_session,acceptance_epoch,accepted_boundary_ordinal,opening_snapshot_sequence,closing_snapshot_sequence,opening_reference_sequence,closing_reference_sequence,opening_reference_timestamp_ticks,closing_reference_timestamp_ticks,time_domain,source_count_first_sequence,source_count_last_sequence,source_count_record_count,counted_edges,excluded_candidate_count,nominal_interval_count,acceptance_policy_sha256"
#define OTIS_CONTRACT_ACCEPTED_PPS_SPANS_V1_SCHEMA_VERSION 1u
#define OTIS_CONTRACT_ACCEPTED_PPS_SPANS_V1_FIELD_COUNT 19u
#define OTIS_CONTRACT_CONTROL_PREVIEWS_V1_HEADER "record_type,schema_version,control_seq,decision_id,decision_timestamp_ticks,time_domain,est_input_ref,plant_model_ref,plant_model_id,plant_model_version,plant_model_hash,policy_version,config_hash,control_state,previous_control_state,state_transition,transition_reason_code,preview_eligibility,eligibility_reason_codes,diagnostic_health,model_applicability,model_reason_codes,current_dac_code,frequency_error_hz,hz_per_code,raw_delta_codes,limited_delta_codes,proposed_dac_code,step_limited,range_clamped,preview_available,preview_only,actuation_authorized,actionable,decision_reason_code"
#define OTIS_CONTRACT_CONTROL_PREVIEWS_V1_SCHEMA_VERSION 1u
#define OTIS_CONTRACT_CONTROL_PREVIEWS_V1_FIELD_COUNT 35u
#define OTIS_CONTRACT_COUNT_OBSERVATIONS_V1_HEADER "record_type,schema_version,count_seq,channel_id,gate_open_ticks,gate_close_ticks,gate_domain,counted_edges,source_edge,source_domain,flags"
#define OTIS_CONTRACT_COUNT_OBSERVATIONS_V1_SCHEMA_VERSION 1u
#define OTIS_CONTRACT_COUNT_OBSERVATIONS_V1_FIELD_COUNT 11u
#define OTIS_CONTRACT_DAC_STEPS_V1_HEADER "record_type,schema_version,seq,elapsed_ms,step_index,dac_code_requested,dac_code_applied,dac_code_clamped,dac_voltage_measured_v,ocxo_tune_voltage_measured_v,dwell_ms,event,flags"
#define OTIS_CONTRACT_DAC_STEPS_V1_SCHEMA_VERSION 1u
#define OTIS_CONTRACT_DAC_STEPS_V1_FIELD_COUNT 13u
#define OTIS_CONTRACT_ENVIRONMENT_V1_HEADER "record_type,schema_version,env_seq,timestamp_ticks,observation_domain,source,role,temperature_c,relative_humidity_pct,pressure_pa,flags"
#define OTIS_CONTRACT_ENVIRONMENT_V1_SCHEMA_VERSION 1u
#define OTIS_CONTRACT_ENVIRONMENT_V1_FIELD_COUNT 11u
#define OTIS_CONTRACT_ESTIMATES_V3_HEADER "record_type,schema_version,estimate_seq,estimate_id,estimator_timestamp_ticks,time_domain,capture_session,source_acceptance_epoch,source_opening_accepted_boundary_ordinal,source_closing_accepted_boundary_ordinal,source_opening_snapshot_sequence,source_closing_snapshot_sequence,source_opening_reference_sequence,source_closing_reference_sequence,source_accepted_spans_ref,source_status_refs,source_dac_ref,manifest_ref,estimator_version,config_hash,observation_validity,observation_reason_codes,reference_validity,reference_age_s,reference_continuity,count_validity,count_age_s,count_continuity,diagnostic_health,diagnostic_reason_codes,frequency_observation_hz,accepted_sample_count,estimator_confidence,frequency_estimate_hz,frequency_error_hz,dispersion_hz,uncertainty_status,uncertainty_reason_codes,count_quantization_standard_uncertainty_hz,counter_aperture_standard_uncertainty_hz,reference_standard_uncertainty_hz,calibration_standard_uncertainty_hz,model_standard_uncertainty_hz,combined_standard_uncertainty_hz,coverage_factor,expanded_uncertainty_hz,correlation_policy,uncertainty_model_ref,drift_enabled,drift_hz_per_s,preview_eligibility,eligibility_reason_codes"
#define OTIS_CONTRACT_ESTIMATES_V3_SCHEMA_VERSION 3u
#define OTIS_CONTRACT_ESTIMATES_V3_FIELD_COUNT 52u
#define OTIS_CONTRACT_FORWARDED_MONITOR_SNAPSHOTS_V1_HEADER "record_type,schema_version,session,reference_session,snapshot_sequence,cumulative_down_counter,reference_sequence,reference_timestamp_ticks,status,backend,channel_id"
#define OTIS_CONTRACT_FORWARDED_MONITOR_SNAPSHOTS_V1_SCHEMA_VERSION 1u
#define OTIS_CONTRACT_FORWARDED_MONITOR_SNAPSHOTS_V1_FIELD_COUNT 11u
#define OTIS_CONTRACT_HEALTH_V1_HEADER "record_type,schema_version,status_seq,timestamp_ticks,status_domain,component,status_key,status_value,severity,flags"
#define OTIS_CONTRACT_HEALTH_V1_SCHEMA_VERSION 1u
#define OTIS_CONTRACT_HEALTH_V1_FIELD_COUNT 10u
#define OTIS_CONTRACT_INSTRUMENT_APPLICATION_V2_HEADER "record_type,schema_version,record_sequence,session,capture_session,sequence,dac_epoch,requested_code,applied_code,attempted,ok,accepted,rejection,timestamp_ticks,timestamp_domain"
#define OTIS_CONTRACT_INSTRUMENT_APPLICATION_V2_SCHEMA_VERSION 2u
#define OTIS_CONTRACT_INSTRUMENT_APPLICATION_V2_FIELD_COUNT 15u
#define OTIS_CONTRACT_INSTRUMENT_COMMAND_V2_HEADER "record_type,schema_version,record_sequence,session,sequence,mode,code,dwell_s,receipt,command_completed,timestamp_ticks,timestamp_domain"
#define OTIS_CONTRACT_INSTRUMENT_COMMAND_V2_SCHEMA_VERSION 2u
#define OTIS_CONTRACT_INSTRUMENT_COMMAND_V2_FIELD_COUNT 12u
#define OTIS_CONTRACT_INSTRUMENT_DECISION_V2_HEADER "record_type,schema_version,record_sequence,session,capture_session,sequence,timestamp_ticks,acceptance_epoch,opening_accepted_boundary,closing_accepted_boundary,dac_epoch,applied_code,delta_codes,requested_code,edge_error_counts,phase_epoch,relative_phase_cycles,phase_valid,tight_inside,authority_valid,settled,metadata_qualified,raw_fll_picocodes,raw_pll_picocodes,debt_fll_picocodes,debt_pll_picocodes,reason"
#define OTIS_CONTRACT_INSTRUMENT_DECISION_V2_SCHEMA_VERSION 2u
#define OTIS_CONTRACT_INSTRUMENT_DECISION_V2_FIELD_COUNT 27u
#define OTIS_CONTRACT_INSTRUMENT_RESPONSE_V2_HEADER "record_type,schema_version,record_sequence,session,capture_session,sequence,dac_epoch,delta_codes,classification,reason,timestamp_ticks,acceptance_epoch,opening_accepted_boundary,closing_accepted_boundary,timestamp_domain"
#define OTIS_CONTRACT_INSTRUMENT_RESPONSE_V2_SCHEMA_VERSION 2u
#define OTIS_CONTRACT_INSTRUMENT_RESPONSE_V2_FIELD_COUNT 15u
#define OTIS_CONTRACT_INSTRUMENT_STATE_V2_HEADER "record_type,schema_version,record_sequence,session,capture_session,mode,requested_mode,state,reason,acceptance_epoch,accepted_boundary,metadata_sequence,reference_hold,metadata_hold,response_incomplete,applied_code,dac_epoch,timestamp_ticks,timestamp_domain"
#define OTIS_CONTRACT_INSTRUMENT_STATE_V2_SCHEMA_VERSION 2u
#define OTIS_CONTRACT_INSTRUMENT_STATE_V2_FIELD_COUNT 19u
#define OTIS_CONTRACT_INSTRUMENT_WRITE_V2_HEADER "record_type,schema_version,record_sequence,session,capture_session,sequence,dac_epoch,prior_code,requested_code,prior_known,kind,deadline_ticks,decision_sequence,command_sequence,timestamp_domain"
#define OTIS_CONTRACT_INSTRUMENT_WRITE_V2_SCHEMA_VERSION 2u
#define OTIS_CONTRACT_INSTRUMENT_WRITE_V2_FIELD_COUNT 15u
#define OTIS_CONTRACT_PHASE_ESTIMATOR_OUTPUTS_V2_HEADER "record_type,schema_version,phase_epoch,observation_sequence,capture_session,acceptance_epoch,accepted_boundary_ordinal,source_relative_phase_observation,raw_relative_phase_cycles,raw_relative_phase_time_ns,filtered_relative_phase_cycles,estimated_frequency_error_hz,estimator_id,configuration_sha256,estimate_age_s,qualification_state,uncertainty_status,reason_codes"
#define OTIS_CONTRACT_PHASE_ESTIMATOR_OUTPUTS_V2_SCHEMA_VERSION 2u
#define OTIS_CONTRACT_PHASE_ESTIMATOR_OUTPUTS_V2_FIELD_COUNT 18u
#define OTIS_CONTRACT_PPS_SNAPSHOTS_V2_HEADER "record_type,schema_version,session,snapshot_sequence,cumulative_down_counter,reference_sequence,reference_timestamp_ticks,timestamp_uncertainty_ticks,status,backend"
#define OTIS_CONTRACT_PPS_SNAPSHOTS_V2_SCHEMA_VERSION 2u
#define OTIS_CONTRACT_PPS_SNAPSHOTS_V2_FIELD_COUNT 10u
#define OTIS_CONTRACT_RAW_EVENTS_V1_HEADER "record_type,schema_version,event_seq,channel_id,edge,timestamp_ticks,capture_domain,flags"
#define OTIS_CONTRACT_RAW_EVENTS_V1_SCHEMA_VERSION 1u
#define OTIS_CONTRACT_RAW_EVENTS_V1_FIELD_COUNT 8u
#define OTIS_CONTRACT_RELATIVE_PHASE_OBSERVATIONS_V2_HEADER "record_type,schema_version,phase_epoch,observation_sequence,capture_session,acceptance_epoch,accepted_boundary_ordinal,source_accepted_span_ref,opening_snapshot_sequence,closing_snapshot_sequence,opening_reference_sequence,closing_reference_sequence,dac_epoch,source_backend,source_file_sha256,method_id,configuration_sha256,interval_edges,edge_error_cycles,relative_phase_cycles,relative_phase_time_ns,qualification_state,observation_age_s,discontinuity_reason,calibrated_uncertainty_status"
#define OTIS_CONTRACT_RELATIVE_PHASE_OBSERVATIONS_V2_SCHEMA_VERSION 2u
#define OTIS_CONTRACT_RELATIVE_PHASE_OBSERVATIONS_V2_FIELD_COUNT 25u
#define OTIS_CONTRACT_TIGHT_DEADBAND_DECISIONS_V1_HEADER "record_type,schema_version,decision_sequence,estimate_id,decision_timestamp_ticks,time_domain,capture_session,dac_epoch,integer_edge_error_counts,absolute_edge_error_counts,state_before,state_after,entry_counter,release_counter,transition,frequency_controller_eligible,requalified,requalification_reason,three_count_band_inside,two_count_band_inside,policy_id,policy_sha256,actionable,actuation_authorized,authorization_consumed,reason_codes"
#define OTIS_CONTRACT_TIGHT_DEADBAND_DECISIONS_V1_SCHEMA_VERSION 1u
#define OTIS_CONTRACT_TIGHT_DEADBAND_DECISIONS_V1_FIELD_COUNT 26u

#define OTIS_ACTIVE_STATUS_CONTRACT_ID "OTIS_INSTRUMENT_STATUS_V2"
#define OTIS_ACTIVE_STATUS_COMPONENT "adaptive_hybrid"
#define OTIS_ACTIVE_STATUS_FIELD_COUNT 36u
#define OTIS_ACTIVE_STATUS_ENVELOPE_COUNT 3u
#define OTIS_ACTIVE_STATUS_BURST_COUNT 39u
#define OTIS_EVIDENCE_SELECTED_PREFIX_COUNT 3u
#define OTIS_EVIDENCE_SELECTED_SUFFIX_COUNT 1u
#define OTIS_EVIDENCE_REQUEST_DECISION_COUNT 3u
#define OTIS_EVIDENCE_RESPONSE_DECISION_COUNT 2u
#define OTIS_EVIDENCE_RESPONSE_COMPLETION_COUNT 2u
#define OTIS_EVIDENCE_ACCEPTED_SPAN_COUNT 1u
#define OTIS_EVIDENCE_FAIL_TRANSITION_COUNT 1u
#define OTIS_EVIDENCE_REQUEST_FRONTIER 7u
#define OTIS_EVIDENCE_RESPONSE_FRONTIER 8u
#define OTIS_EVIDENCE_METADATA_TRANSITION_COUNT 1u
#define OTIS_EVIDENCE_METADATA_RESPONSE_FRONTIER 10u
#define OTIS_EVIDENCE_REQUEST_FAIL_FRONTIER 8u
#define OTIS_EVIDENCE_QUEUE_DEPTH 16u
#define OTIS_ESTIMATE_TO_DECISION_MAXIMUM_LAG_TICKS 60000000ull
#define OTIS_TELEMETRY_NONACTIVE_TIMING_HEALTH_COUNT 92u
#define OTIS_TELEMETRY_MAXIMUM_CONCURRENT_COUNT 170u
#define OTIS_TELEMETRY_MAXIMUM_BOOT_COUNT 187u
#define OTIS_TELEMETRY_QUEUE_DEPTH 197u
#define OTIS_COMMAND_ACTIVE_MODE_PREFIX "ACTIVE MODE"
#define OTIS_COMMAND_ACTIVE_MODE_PREFIX_LENGTH 11u
#define OTIS_COMMAND_ACTIVE_MODE_ARGUMENT_COUNT 5u
#define OTIS_COMMAND_ACTIVE_SNAPSHOT_PREFIX "ACTIVE SNAPSHOT"
#define OTIS_COMMAND_ACTIVE_SNAPSHOT_PREFIX_LENGTH 15u
#define OTIS_COMMAND_ACTIVE_SNAPSHOT_ARGUMENT_COUNT 1u

#endif
