// Generated by tools/generate_plant_model_binding.py.
// Source: profiles/plant_models/cx317_h1_bench_v3.json
// Do not edit by hand; regenerate only after validating the source artifact.
#ifndef OTIS_PLANT_MODEL_V4_GENERATED_H
#define OTIS_PLANT_MODEL_V4_GENERATED_H

#include <stdint.h>

constexpr char kPlantModelRef[] = "profiles/plant_models/cx317_h1_bench_v3.json";
constexpr char kPlantModelId[] = "cx317_h1_bench";
constexpr char kPlantModelHash[] =
    "900af6b2ec325f99798db043df964a28a36ac2a2209669c7f4b7d569efbf161d";
constexpr uint32_t kPlantModelSchemaVersion = 1u;
constexpr uint32_t kPlantModelVersion = 4u;
constexpr bool kPlantModelStructurallyValid = true;
constexpr bool kPlantModelSemanticallyValid = true;
constexpr bool kPlantModelControlReady = false;
constexpr bool kPlantModelActuationEnabled = false;
constexpr char kPlantModelTopologyId[] =
    "h1_run_020_g17_reworked_d14_d10_pps_witness";
constexpr char kPlantModelApplicabilityMode[] =
    "observe_only";
constexpr char kPlantModelMeasurementBackend[] =
    "OTIS_TCXO_COUNTER_BACKEND_PIO_LONG_GATE";
constexpr double kPlantModelGateDurationS = 300;
constexpr double kPlantModelSettlingExclusionS =
    900;
constexpr double kPlantModelTemperatureMinC =
    28.445;
constexpr double kPlantModelTemperatureMaxC =
    30.455;
constexpr uint32_t kPlantModelExcludedCountSequences[] = {77u};
constexpr uint32_t kPlantModelExcludedCountSequenceCount = 1u;
constexpr char kPlantModelEstimatorVersion[] =
    "LOCAL_PPS_BOUNDARY_INTERPOLATED_V1";
constexpr char kPlantModelEstimatorMethodHash[] =
    "af4afcb01f9f22b2f1102d278cf17a80d15f37f72da4016666d4278e4fb37e3b";
constexpr char kPlantModelEstimatorTimingDomain[] =
    "rp2040_timer0";
constexpr char kPlantModelEstimatorExtrapolationPolicy[] =
    "prohibited";
constexpr double kPlantModelReferenceIntervalMinS =
    0.8;
constexpr double kPlantModelReferenceIntervalMaxS =
    1.2;
constexpr uint32_t kPlantModelReferenceInvalidFlagMask =
    4143u;
constexpr uint16_t kModelApplicabilityMin = 0xA800u;
constexpr uint16_t kModelApplicabilityMax = 0xB400u;
constexpr uint16_t kManualSafeMin = 0xA800u;
constexpr uint16_t kManualSafeMax = 0xB400u;
constexpr uint16_t kCandidateMin = 0xA800u;
constexpr uint16_t kCandidateMax = 0xAB00u;
constexpr uint16_t kMaximumPreviewStep = 0x0300u;
constexpr double kHzPerCode = 0.0001673035127775317;

#endif
