#ifndef OTIS_PROTOCOL_H
#define OTIS_PROTOCOL_H

#include <stdint.h>

#define OTIS_SCHEMA_VERSION_V1 1u

#define OTIS_CHANNEL_GENERIC_EVENT 0u
#define OTIS_CHANNEL_PPS_REFERENCE 1u
#define OTIS_CHANNEL_OSC_OBSERVATION 2u

#define OTIS_DOMAIN_RP2040_TIMER0 "rp2040_timer0"
#define OTIS_DOMAIN_H0_TCXO_16MHZ "h0_tcxo_16mhz"

#define OTIS_EDGE_RISING "R"
#define OTIS_EDGE_FALLING "F"
#define OTIS_EDGE_BOTH_OR_UNSPECIFIED "B"

#define OTIS_SEVERITY_INFO "INFO"
#define OTIS_SEVERITY_WARN "WARN"
#define OTIS_SEVERITY_ERROR "ERROR"
#define OTIS_SEVERITY_FATAL "FATAL"

#define OTIS_RECORD_EVT "EVT"
#define OTIS_RECORD_REF "REF"
#define OTIS_RECORD_CNT "CNT"
#define OTIS_RECORD_STS "STS"

#define OTIS_SW1_MODE_SYNTHETIC_USB 1
#define OTIS_SW1_MODE_GPIO_LOOPBACK 2
#define OTIS_SW1_MODE_GPS_PPS 3
#define OTIS_SW1_MODE_TCXO_OBSERVE 4

#ifndef OTIS_SW1_BRINGUP_MODE
#define OTIS_SW1_BRINGUP_MODE OTIS_SW1_MODE_SYNTHETIC_USB
#endif

#define OTIS_TCXO_COUNTER_BACKEND_FC0_GPIN0 1
#define OTIS_TCXO_COUNTER_BACKEND_GPIO_IRQ 2

#ifndef OTIS_TCXO_COUNTER_BACKEND
#define OTIS_TCXO_COUNTER_BACKEND OTIS_TCXO_COUNTER_BACKEND_FC0_GPIN0
#endif

#if OTIS_TCXO_COUNTER_BACKEND != OTIS_TCXO_COUNTER_BACKEND_FC0_GPIN0 && \
    OTIS_TCXO_COUNTER_BACKEND != OTIS_TCXO_COUNTER_BACKEND_GPIO_IRQ
#error "OTIS_TCXO_COUNTER_BACKEND must be FC0_GPIN0 or GPIO_IRQ."
#endif

#if OTIS_SW1_BRINGUP_MODE != OTIS_SW1_MODE_SYNTHETIC_USB && \
    OTIS_SW1_BRINGUP_MODE != OTIS_SW1_MODE_GPIO_LOOPBACK && \
    OTIS_SW1_BRINGUP_MODE != OTIS_SW1_MODE_GPS_PPS && \
    OTIS_SW1_BRINGUP_MODE != OTIS_SW1_MODE_TCXO_OBSERVE
#error "OTIS_SW1_BRINGUP_MODE must be one of the OTIS_SW1_MODE_* constants."
#endif

typedef enum OtisFlagsV1 {
  OTIS_FLAG_NONE = 0u,
  OTIS_FLAG_CAPTURE_OVERFLOW_NEARBY = 1u << 0,
  OTIS_FLAG_CAPTURE_RING_OVERRUN = 1u << 1,
  OTIS_FLAG_EDGE_ORDER_SUSPECT = 1u << 2,
  OTIS_FLAG_REFERENCE_VALIDITY_SUSPECT = 1u << 3,
  OTIS_FLAG_TIMESTAMP_RECONSTRUCTED = 1u << 4,
  OTIS_FLAG_SOURCE_HEALTH_SUSPECT = 1u << 5,
  OTIS_FLAG_PULSE_TOO_NARROW = 1u << 6,
  OTIS_FLAG_PULSE_TOO_WIDE = 1u << 7,
  OTIS_FLAG_RATE_TOO_HIGH = 1u << 8,
  OTIS_FLAG_INPUT_STUCK_LOW = 1u << 9,
  OTIS_FLAG_INPUT_STUCK_HIGH = 1u << 10,
  OTIS_FLAG_DEBOUNCE_REJECTED = 1u << 11,
  OTIS_FLAG_GATE_INCOMPLETE = 1u << 12,
  OTIS_FLAG_COUNT_SATURATED = 1u << 13,
  OTIS_FLAG_HOST_DERIVED = 1u << 14,
  OTIS_FLAG_PROFILE_ASSUMPTION = 1u << 15,
  OTIS_FLAG_RESERVED_MASK = 0xFFFF0000u,
} OtisFlagsV1;

#endif
