#ifndef OTIS_CONFIG_H
#define OTIS_CONFIG_H

// This is the Arduino IDE-friendly configuration surface for the OTIS SW1
// smoke firmware. Protocol constants and board pin contracts live elsewhere.

#if defined(ARDUINO)
#if __has_include("otis_build_profile.generated.h")
#include "otis_build_profile.generated.h"
#else
#error "Generate an Arduino profile first: python3 tools/firmware_matrix.py --prepare-ide --profile <profile_id>"
#endif
#endif

// SW1 bring-up modes.
#define OTIS_SW1_MODE_SYNTHETIC_USB 1
#define OTIS_SW1_MODE_GPIO_LOOPBACK 2
#define OTIS_SW1_MODE_GPS_PPS 3
#define OTIS_SW1_MODE_TCXO_OBSERVE 4
#define OTIS_SW1_MODE_H1_OCXO_OBSERVE 5

#ifndef OTIS_SW1_BRINGUP_MODE
#define OTIS_SW1_BRINGUP_MODE OTIS_SW1_MODE_H1_OCXO_OBSERVE
#endif

// Declared before provenance so an explicit preview build names itself
// accurately in boot/status and derived-record provenance.
#ifndef OTIS_ENABLE_PHASE4_OBSERVE_PREVIEW
#define OTIS_ENABLE_PHASE4_OBSERVE_PREVIEW 0
#endif

#ifndef OTIS_ENABLE_CX317_I_ONLY_PREVIEW
#define OTIS_ENABLE_CX317_I_ONLY_PREVIEW 0
#endif

// Stage 6 dedicates Arduino-Pico Core 0 to services/I/O and Core 1 to timing,
// estimation and control preview.  It remains disabled for all legacy and
// single-core profiles.
#ifndef OTIS_ENABLE_DUAL_CORE_PARTITION
#define OTIS_ENABLE_DUAL_CORE_PARTITION 0
#endif

// Bounded active control is structurally available only in the exact Stage 5
// single-core and Stage 7 dual-core programme profiles. Existing/default/
// preview profiles leave this disabled and therefore have no controller-to-DAC
// call path.
#ifndef OTIS_ENABLE_CX317_BOUNDED_ACTIVE
#define OTIS_ENABLE_CX317_BOUNDED_ACTIVE 0
#endif

#define OTIS_CX317_ACTIVE_CAMPAIGN_NONE 0
#define OTIS_CX317_ACTIVE_CAMPAIGN_A 1
#define OTIS_CX317_ACTIVE_CAMPAIGN_B 2
#define OTIS_CX317_ACTIVE_CAMPAIGN_STAGE7_A 3
#define OTIS_CX317_ACTIVE_CAMPAIGN_STAGE7_B 4
#define OTIS_CX317_ACTIVE_CAMPAIGN_STAGE7_REHEARSAL 5

#ifndef OTIS_CX317_ACTIVE_CAMPAIGN
#define OTIS_CX317_ACTIVE_CAMPAIGN OTIS_CX317_ACTIVE_CAMPAIGN_NONE
#endif

#ifndef OTIS_CX317_ACTIVE_START_CODE
#define OTIS_CX317_ACTIVE_START_CODE 0u
#endif

#ifndef OTIS_CX317_ACTIVE_CORRECTION_LIMIT
#define OTIS_CX317_ACTIVE_CORRECTION_LIMIT 0u
#endif

#ifndef OTIS_CX317_ACTIVE_CUMULATIVE_LIMIT_CODES
#define OTIS_CX317_ACTIVE_CUMULATIVE_LIMIT_CODES 0u
#endif

// The exact Stage 7 qualification profiles retain the frozen production
// timings below.  The separately identified rehearsal profile overrides them
// to traverse the same live dual-core sequence quickly; its records are
// diagnostic-only and cannot satisfy a Stage 7 qualification identity.
#ifndef OTIS_CX317_SELECTED_SPAN_INTERVALS_CONFIG
#define OTIS_CX317_SELECTED_SPAN_INTERVALS_CONFIG 600u
#endif

#ifndef OTIS_CX317_STARTUP_WARMUP_S
#define OTIS_CX317_STARTUP_WARMUP_S 1800u
#endif

#ifndef OTIS_CX317_SETTLING_EXCLUSION_S
#define OTIS_CX317_SETTLING_EXCLUSION_S 900u
#endif

#ifndef OTIS_CX317_FULL_HISTORY_RESET_S
#define OTIS_CX317_FULL_HISTORY_RESET_S 1500u
#endif

#ifndef OTIS_CX317_RECOVERY_FRESH_SUPPORT_S
#define OTIS_CX317_RECOVERY_FRESH_SUPPORT_S 600u
#endif

#ifndef OTIS_CX317_DECISION_CADENCE_S
#define OTIS_CX317_DECISION_CADENCE_S 1800u
#endif

#ifndef OTIS_CX317_MINIMUM_APPLIED_CADENCE_S
#define OTIS_CX317_MINIMUM_APPLIED_CADENCE_S 1800u
#endif

#ifndef OTIS_ENABLE_GNSS_RECEIVER
#define OTIS_ENABLE_GNSS_RECEIVER 0
#endif

// Firmware provenance is supplied by the pinned matrix builder or its explicit
// Arduino IDE profile generator. A hand-maintained source literal is not
// evidence of the tree or toolchain that produced a binary. Host-only C++
// harnesses do not produce firmware and use a conspicuous non-firmware profile
// token so they can exercise shared logic.
#if defined(ARDUINO)
#ifndef OTIS_BUILD_PROFILE_GENERATED
#error "Build with tools/firmware_matrix.py or generate an IDE profile with --prepare-ide; generated provenance is required."
#endif

#ifndef OTIS_BUILD_PROVENANCE_FORMAT
#error "OTIS_BUILD_PROVENANCE_FORMAT must be generated by the firmware matrix builder."
#endif

#ifndef OTIS_BUILD_GIT_COMMIT
#error "OTIS_BUILD_GIT_COMMIT must be generated by the firmware matrix builder."
#endif

#ifndef OTIS_BUILD_SOURCE_STATE
#error "OTIS_BUILD_SOURCE_STATE must be generated by the firmware matrix builder."
#endif

#ifndef OTIS_BUILD_SOURCE_SHA256
#error "OTIS_BUILD_SOURCE_SHA256 must be generated by the firmware matrix builder."
#endif

#ifndef OTIS_BUILD_CONFIG_SHA256
#error "OTIS_BUILD_CONFIG_SHA256 must be generated by the firmware matrix builder."
#endif

#ifndef OTIS_BUILD_PROFILE_ID
#error "OTIS_BUILD_PROFILE_ID must be generated by the firmware matrix builder."
#endif

#ifndef OTIS_BUILD_FQBN
#error "OTIS_BUILD_FQBN must be generated by the firmware matrix builder."
#endif

#ifndef OTIS_BUILD_BOARD_ID
#error "OTIS_BUILD_BOARD_ID must be generated by the firmware matrix builder."
#endif

#ifndef OTIS_BUILD_BOARD_NAME
#error "OTIS_BUILD_BOARD_NAME must be generated by the firmware matrix builder."
#endif

#ifndef OTIS_BUILD_CORE_PROVIDER
#error "OTIS_BUILD_CORE_PROVIDER must be generated by the firmware matrix builder."
#endif

#ifndef OTIS_BUILD_CORE_VERSION
#error "OTIS_BUILD_CORE_VERSION must be generated by the firmware matrix builder."
#endif

#ifndef OTIS_BUILD_CORE_INSTALLED_SHA256
#error "OTIS_BUILD_CORE_INSTALLED_SHA256 must be generated by the firmware matrix builder."
#endif

#ifndef OTIS_BUILD_TOOLCHAIN
#error "OTIS_BUILD_TOOLCHAIN must be generated by the firmware matrix builder."
#endif

#ifndef OTIS_BUILD_COMPILER
#error "OTIS_BUILD_COMPILER must be generated by the firmware matrix builder."
#endif

#ifndef OTIS_BUILD_TOOLCHAIN_INSTALLED_SHA256
#error "OTIS_BUILD_TOOLCHAIN_INSTALLED_SHA256 must be generated by the firmware matrix builder."
#endif

#ifndef OTIS_BUILD_ARDUINO_CLI_VERSION
#error "OTIS_BUILD_ARDUINO_CLI_VERSION must be generated by the firmware matrix builder."
#endif

#ifndef OTIS_BUILD_INVOCATION_ID
#error "OTIS_BUILD_INVOCATION_ID must be generated by the firmware matrix builder."
#endif
#else
#ifndef OTIS_BUILD_PROFILE_ID
#define OTIS_BUILD_PROFILE_ID "host_test_non_firmware"
#endif
#ifndef OTIS_BUILD_GIT_COMMIT
#define OTIS_BUILD_GIT_COMMIT "host_test_non_firmware"
#endif
#ifndef OTIS_BUILD_BOARD_ID
#define OTIS_BUILD_BOARD_ID "host_test_non_firmware"
#endif
#ifndef OTIS_BUILD_BOARD_NAME
#define OTIS_BUILD_BOARD_NAME "host_test_non_firmware"
#endif
#endif

#ifndef OTIS_FIRMWARE_NAME
#define OTIS_FIRMWARE_NAME "otis_nano_rp2040_connect"
#endif

#ifndef OTIS_FIRMWARE_VERSION
#if OTIS_ENABLE_DUAL_CORE_PARTITION && OTIS_ENABLE_CX317_BOUNDED_ACTIVE
#define OTIS_FIRMWARE_VERSION "CX317_DUAL_CORE_ACTIVE_I_ONLY_V1"
#elif OTIS_ENABLE_CX317_BOUNDED_ACTIVE
#define OTIS_FIRMWARE_VERSION "CX317_BOUNDED_ACTIVE_I_ONLY_V2"
#elif OTIS_ENABLE_DUAL_CORE_PARTITION
#define OTIS_FIRMWARE_VERSION "CX317_DUAL_CORE_POST_CAMPAIGN_PREVIEW_V1"
#elif OTIS_ENABLE_CX317_I_ONLY_PREVIEW
#define OTIS_FIRMWARE_VERSION "CX317_PPS_GATED_I_ONLY_PREVIEW_V2"
#elif OTIS_ENABLE_GNSS_RECEIVER
#define OTIS_FIRMWARE_VERSION "CX317_PPS_GATED_GNSS_SMOKE_V1"
#elif OTIS_ENABLE_PHASE4_OBSERVE_PREVIEW
#define OTIS_FIRMWARE_VERSION "SW2_PHASE4_OBSERVE_PREVIEW"
#else
#define OTIS_FIRMWARE_VERSION "SW1"
#endif
#endif

#ifndef OTIS_FIRMWARE_CONFIG_ID
#define OTIS_FIRMWARE_CONFIG_ID OTIS_BUILD_PROFILE_ID
#endif

#ifndef OTIS_FIRMWARE_GIT_COMMIT
#define OTIS_FIRMWARE_GIT_COMMIT OTIS_BUILD_GIT_COMMIT
#endif

// Edge capture backends. Keep IRQ as the default SW1 path; PIO FIFO is an
// opt-in SW1.5a experiment and still uses CPU-attached timestamps.
//
// Guardrail: the PIO FIFO backend is only for sparse edge streams such as PPS,
// slow GPIO loopback, or future low-rate event inputs. It must not be used to
// enqueue raw 10 MHz / 16 MHz CXO edges. Raw oscillator input on D8 / GPIO20 /
// GPIN0 should use the RP2040 frequency-counter / FC0 / gated-count path.
#define OTIS_CAPTURE_BACKEND_IRQ 1
#define OTIS_CAPTURE_BACKEND_PIO_FIFO 2

#ifndef OTIS_CAPTURE_BACKEND
#define OTIS_CAPTURE_BACKEND OTIS_CAPTURE_BACKEND_IRQ
#endif

#ifndef OTIS_CAPTURE_MODE
#if OTIS_CAPTURE_BACKEND == OTIS_CAPTURE_BACKEND_PIO_FIFO
#define OTIS_CAPTURE_MODE "pio_fifo_cpu_timestamped"
#else
#define OTIS_CAPTURE_MODE "irq_reconstructed"
#endif
#endif

#ifndef OTIS_NOMINAL_CAPTURE_CLOCK_HZ
#define OTIS_NOMINAL_CAPTURE_CLOCK_HZ 16000000u
#endif

// Conservative full-wrap exclusion bound for the PPS snapshot counter. The
// PIO can execute at most one X decrement per 133 MHz system clock, so this is
// an architectural upper bound on captured edges, not an oscillator estimate
// or clean-run acceptance tolerance.
#ifndef OTIS_PPS_SNAPSHOT_MAX_CAPTURED_EDGE_RATE_HZ
#define OTIS_PPS_SNAPSHOT_MAX_CAPTURED_EDGE_RATE_HZ 133000000u
#endif

#ifndef OTIS_NOMINAL_TCXO_HZ
#define OTIS_NOMINAL_TCXO_HZ 16000000u
#endif

#ifndef OTIS_NOMINAL_OCXO_HZ
#define OTIS_NOMINAL_OCXO_HZ 10000000u
#endif

#ifndef OTIS_NOMINAL_PPS_HZ
#define OTIS_NOMINAL_PPS_HZ 1u
#endif

// TCXO observation backends. FC0/GPIN0 is the simple RP2040 clock-counter path;
// H1 long-gate PIO is the raw-edge metrology path for resolving sub-Hz VCOCXO
// DAC response; GPIO IRQ is only for deliberately divided, interrupt-safe test
// signals. PPS-gated ratio is a raw count-observation backend that uses PPS
// edges to bound the oscillator count window and leaves ratio/frequency
// derivation to host tooling.
#define OTIS_TCXO_COUNTER_BACKEND_FC0_GPIN0 1
#define OTIS_TCXO_COUNTER_BACKEND_GPIO_IRQ 2
#define OTIS_TCXO_COUNTER_BACKEND_PIO_LONG_GATE 3
#define OTIS_TCXO_COUNTER_BACKEND_PPS_GATED_RATIO 4

#ifndef OTIS_TCXO_COUNTER_BACKEND
#if OTIS_SW1_BRINGUP_MODE == OTIS_SW1_MODE_H1_OCXO_OBSERVE
#define OTIS_TCXO_COUNTER_BACKEND OTIS_TCXO_COUNTER_BACKEND_PPS_GATED_RATIO
#else
#define OTIS_TCXO_COUNTER_BACKEND OTIS_TCXO_COUNTER_BACKEND_FC0_GPIN0
#endif
#endif

// Boot and serial behavior.
#ifndef OTIS_BOOT_INITIAL_DELAY_MS
#define OTIS_BOOT_INITIAL_DELAY_MS 1500u
#endif

#ifndef OTIS_SERIAL_BAUD
#define OTIS_SERIAL_BAUD 115200u
#endif

#ifndef OTIS_SERIAL_WAIT_MS
#define OTIS_SERIAL_WAIT_MS 250u
#endif

#ifndef OTIS_SAFE_MODE_FAILURE_THRESHOLD
#define OTIS_SAFE_MODE_FAILURE_THRESHOLD 3u
#endif

// Diagnostics.
#ifndef OTIS_ENABLE_RP2040_BOOT_DIAG
#define OTIS_ENABLE_RP2040_BOOT_DIAG 1
#endif

// Temporary H1 diagnostic scaffolding: when enabled, D10 is tied to the same
// physical PPS signal as D14 and observed as an independent rising-edge witness.
// It must remain disabled for normal generic-event or loopback work.
#ifndef OTIS_ENABLE_PPS_DUAL_OBSERVER
#define OTIS_ENABLE_PPS_DUAL_OBSERVER 1
#endif

// Bench-only deterministic pseudo-PPS source. It is disabled in every normal
// profile, never starts on boot, and only drives D3 after an explicit ARM then
// START command. Idle, stop, reset, completion, and faults leave D3 high-Z.
#ifndef OTIS_ENABLE_PSEUDO_PPS_GENERATOR
#define OTIS_ENABLE_PSEUDO_PPS_GENERATOR 0
#endif

#ifndef OTIS_PPS_DUAL_OBSERVER_SHORT_INTERVAL_TICKS
#define OTIS_PPS_DUAL_OBSERVER_SHORT_INTERVAL_TICKS 8000000ull
#endif

#ifndef OTIS_PPS_DUAL_OBSERVER_LONG_INTERVAL_TICKS
#define OTIS_PPS_DUAL_OBSERVER_LONG_INTERVAL_TICKS 19200000ull
#endif

#ifndef OTIS_PPS_DUAL_OBSERVER_BURST_SHORT_THRESHOLD
#define OTIS_PPS_DUAL_OBSERVER_BURST_SHORT_THRESHOLD 4u
#endif

#ifndef OTIS_PPS_DUAL_OBSERVER_BUFFER_SIZE
#define OTIS_PPS_DUAL_OBSERVER_BUFFER_SIZE 16u
#endif

#if OTIS_PPS_DUAL_OBSERVER_BUFFER_SIZE < 2u || \
    OTIS_PPS_DUAL_OBSERVER_BUFFER_SIZE > 128u || \
    (OTIS_PPS_DUAL_OBSERVER_BUFFER_SIZE & \
     (OTIS_PPS_DUAL_OBSERVER_BUFFER_SIZE - 1u)) != 0u
#error "OTIS_PPS_DUAL_OBSERVER_BUFFER_SIZE must be a power of two from 2 to 128."
#endif

// Status LED.
#ifndef OTIS_ENABLE_STATUS_LED
#define OTIS_ENABLE_STATUS_LED 0
#endif

#ifndef OTIS_ENABLE_STATUS_LED_BOOT_TEST
#define OTIS_ENABLE_STATUS_LED_BOOT_TEST OTIS_ENABLE_STATUS_LED
#endif

// Runtime sizing and timing.
#ifndef OTIS_CAPTURE_RING_SIZE
#define OTIS_CAPTURE_RING_SIZE 32u
#endif

#ifndef OTIS_PPS_COUNT_BOUNDARY_RING_SIZE
#define OTIS_PPS_COUNT_BOUNDARY_RING_SIZE 128u
#endif

#ifndef OTIS_STATUS_PERIOD_MS
#define OTIS_STATUS_PERIOD_MS 1000u
#endif

#ifndef OTIS_PPS_GATE_STATUS_PERIOD_MS
#define OTIS_PPS_GATE_STATUS_PERIOD_MS 10000u
#endif

#ifndef OTIS_LOOPBACK_TOGGLE_PERIOD_MS
#define OTIS_LOOPBACK_TOGGLE_PERIOD_MS 250u
#endif

#ifndef OTIS_TCXO_GATE_PERIOD_US
#define OTIS_TCXO_GATE_PERIOD_US 10000000u
#endif

// FC0/GPIN0 publishes one CNT observation per gate period. The FC0 hardware
// helper itself is sampled at OTIS_TCXO_MEASURE_PERIOD_MS inside that span, so
// H1 long-gate captures should use a gate much longer than the sample cadence.
#ifndef OTIS_TCXO_MEASURE_PERIOD_MS
#define OTIS_TCXO_MEASURE_PERIOD_MS 1000u
#endif

// H1 slope-metrology long gate. A 300 s raw-edge gate gives about 0.0033 Hz
// edge quantization at 10 MHz and still stays below a 32-bit PIO edge counter.
#ifndef OTIS_H1_LONG_GATE_PERIOD_US
#define OTIS_H1_LONG_GATE_PERIOD_US 300000000u
#endif

#ifndef OTIS_PPS_GATE_MIN_INTERVAL_US
#define OTIS_PPS_GATE_MIN_INTERVAL_US 800000u
#endif

#ifndef OTIS_PPS_GATE_DUPLICATE_MAX_INTERVAL_US
#define OTIS_PPS_GATE_DUPLICATE_MAX_INTERVAL_US 100000u
#endif

#ifndef OTIS_PPS_GATE_MAX_INTERVAL_US
#define OTIS_PPS_GATE_MAX_INTERVAL_US 1200000u
#endif

#ifndef OTIS_PPS_GATE_MISSING_TIMEOUT_US
#define OTIS_PPS_GATE_MISSING_TIMEOUT_US 2500000u
#endif

// This remains zero until the PIO-owned snapshot backend passes the focused
// bench contract. Raw REF/CNT evidence is still emitted while control
// eligibility is structurally inhibited.
#ifndef OTIS_PPS_BOUNDARY_BACKEND_QUALIFIED
#define OTIS_PPS_BOUNDARY_BACKEND_QUALIFIED 0
#endif

#if OTIS_PPS_GATE_MIN_INTERVAL_US == 0u || \
    OTIS_PPS_GATE_MIN_INTERVAL_US > OTIS_PPS_GATE_MAX_INTERVAL_US
#error "PPS gate interval limits must be nonzero and ordered."
#endif

#if OTIS_PPS_GATE_DUPLICATE_MAX_INTERVAL_US == 0u || \
    OTIS_PPS_GATE_DUPLICATE_MAX_INTERVAL_US >= OTIS_PPS_GATE_MIN_INTERVAL_US
#error "PPS duplicate threshold must be nonzero and below the minimum accepted interval."
#endif

#if OTIS_PPS_GATE_MISSING_TIMEOUT_US <= OTIS_PPS_GATE_MAX_INTERVAL_US
#error "PPS missing timeout must exceed the maximum accepted interval."
#endif

// SW2 architectural guardrail: FC0 observations remain visible during startup,
// but they are not eligible for future control/acquire logic until this inhibit
// window has elapsed and enough clean windows have followed it.
#ifndef OTIS_FC0_STARTUP_INHIBIT_MS
#define OTIS_FC0_STARTUP_INHIBIT_MS 600000u
#endif

#ifndef OTIS_FC0_CONTROL_READY_CLEAN_WINDOWS
#define OTIS_FC0_CONTROL_READY_CLEAN_WINDOWS 3u
#endif

// Phase 4 live discipline is an explicitly selected observe-only build.  It
// emits EST/CTL preview telemetry but has no actuation callback and never
// includes the DAC driver.  Manual DAC/sweep ownership remains in the sketch's
// command path.
#ifndef OTIS_PHASE4_PREVIEW_QUEUE_DEPTH
#define OTIS_PHASE4_PREVIEW_QUEUE_DEPTH 4u
#endif

#ifndef OTIS_PHASE4_ESTIMATOR_WINDOW
#define OTIS_PHASE4_ESTIMATOR_WINDOW 5u
#endif

#ifndef OTIS_PHASE4_MINIMUM_ESTIMATOR_SAMPLES
#define OTIS_PHASE4_MINIMUM_ESTIMATOR_SAMPLES 3u
#endif

#ifndef OTIS_PHASE4_RECOVERY_CLEAN_WINDOWS
#define OTIS_PHASE4_RECOVERY_CLEAN_WINDOWS 3u
#endif

#ifndef OTIS_PHASE4_REFERENCE_MAX_AGE_US
#define OTIS_PHASE4_REFERENCE_MAX_AGE_US 1500000u
#endif

#ifndef OTIS_PHASE4_COUNT_MAX_AGE_US
#define OTIS_PHASE4_COUNT_MAX_AGE_US 450000000u
#endif

#ifndef OTIS_PHASE4_MAXIMUM_DISPERSION_HZ
#define OTIS_PHASE4_MAXIMUM_DISPERSION_HZ 0.25
#endif

// H1 open-loop lab instrument DAC support. This is deliberately opt-in and
// operator-initiated; firmware never steers the oscillator from PPS/count
// telemetry.
#ifndef OTIS_ENABLE_DAC_AD5693R
#define OTIS_ENABLE_DAC_AD5693R 0
#endif

// Stage 2 GNSS metadata is deliberately receive-only. The exact installed
// Nano variant maps Serial1 RX to D0/GPIO1 and Serial1 TX to D1/GPIO0. The
// implementation maps only UART0 RX; TX remains a high-impedance input.
#ifndef OTIS_GNSS_UART_TX_ENABLED
#define OTIS_GNSS_UART_TX_ENABLED 0
#endif

#ifndef OTIS_GNSS_UART_BAUD
#define OTIS_GNSS_UART_BAUD 9600u
#endif

#ifndef OTIS_GNSS_SERVICE_BYTE_BUDGET
#define OTIS_GNSS_SERVICE_BYTE_BUDGET 32u
#endif

#ifndef OTIS_GNSS_METADATA_MAX_AGE_MS
#define OTIS_GNSS_METADATA_MAX_AGE_MS 3000u
#endif

#ifndef OTIS_GNSS_RECONNECT_GAP_MS
#define OTIS_GNSS_RECONNECT_GAP_MS 10000u
#endif

#ifndef OTIS_DAC_AD5693R_I2C_ADDRESS
#define OTIS_DAC_AD5693R_I2C_ADDRESS 0x4Cu
#endif

// run_020 IDE-native H1 crossing-characterization envelope. These values live
// in this header deliberately: the Arduino IDE is the required compile/upload
// path, and this run must not depend on command-line -D overrides. The midpoint
// of 0x6000..0xFC00 is 0xAE00, the run_019 broad-fit crossing region. The prior
// code/voltage fit predicts about 0.936..2.450 V across this envelope, within
// the CX317 0..3.3 V operating Vc range. These clamps bound manual commands and
// explicitly started open-loop sweeps; they do not auto-start a sweep, enable
// feedback steering, or authorize SW2 control.
#ifndef OTIS_DAC_MIN_CODE
#define OTIS_DAC_MIN_CODE 0x6000u
#endif

#ifndef OTIS_DAC_MAX_CODE
#define OTIS_DAC_MAX_CODE 0xFC00u
#endif

// Optional low-rate environmental telemetry for oscillator characterization.
// SHT4x is the preferred near-VCOCXO temperature source; BMP280 is primarily
// pressure context and secondary temperature.
#ifndef OTIS_ENABLE_ENV_SENSORS
#define OTIS_ENABLE_ENV_SENSORS 0
#endif

#ifndef OTIS_ENABLE_ENV_SHT4X
#define OTIS_ENABLE_ENV_SHT4X OTIS_ENABLE_ENV_SENSORS
#endif

#ifndef OTIS_ENABLE_ENV_BMP280
#define OTIS_ENABLE_ENV_BMP280 OTIS_ENABLE_ENV_SENSORS
#endif

#ifndef OTIS_ENV_SAMPLE_PERIOD_MS
#define OTIS_ENV_SAMPLE_PERIOD_MS 1000u
#endif

// Phase-4 model applicability treats the primary near-VCOCXO temperature as
// stale after three expected sample periods. This tolerates two consecutive
// delayed/missed low-rate reads without allowing an old value to remain a
// silent applicability input indefinitely.
#ifndef OTIS_PHASE4_TEMPERATURE_MAX_AGE_MS
#define OTIS_PHASE4_TEMPERATURE_MAX_AGE_MS (3u * OTIS_ENV_SAMPLE_PERIOD_MS)
#endif

// The PIO long gate is stopped by foreground service after its configured
// deadline. SHT4x high-precision sampling alone blocks that service for 10 ms.
// Allow five such intervals of aperture latency (0.017% of a 300 s gate);
// larger deviations are observation-quality failures, not model-identity
// mismatches.
#ifndef OTIS_PHASE4_OBSERVED_GATE_TOLERANCE_US
#define OTIS_PHASE4_OBSERVED_GATE_TOLERANCE_US 50000u
#endif

#ifndef OTIS_ENV_SHT4X_I2C_ADDRESS
#define OTIS_ENV_SHT4X_I2C_ADDRESS 0x44u
#endif

#ifndef OTIS_ENV_BMP280_I2C_ADDRESS
#define OTIS_ENV_BMP280_I2C_ADDRESS 0x77u
#endif

// Deterministic H1 open-loop DAC sweep support. This is lab automation only:
// sweeps never start on boot and never steer from count/frequency telemetry.
#ifndef OTIS_ENABLE_H1_DAC_SWEEP
#define OTIS_ENABLE_H1_DAC_SWEEP 0
#endif

#ifndef OTIS_H1_DAC_SWEEP_DEFAULT_DWELL_MS
#define OTIS_H1_DAC_SWEEP_DEFAULT_DWELL_MS 2400000u
#endif

#ifndef OTIS_H1_DAC_SWEEP_SLOPE_DWELL_MS
#define OTIS_H1_DAC_SWEEP_SLOPE_DWELL_MS 2400000u
#endif

#ifndef OTIS_H1_DAC_SWEEP_TINY_STEP_CODES
#define OTIS_H1_DAC_SWEEP_TINY_STEP_CODES 0x0300u
#endif

#ifndef OTIS_H1_DAC_SWEEP_MAX_STEPS
#define OTIS_H1_DAC_SWEEP_MAX_STEPS 16u
#endif

// Boot-hardening test injection. Leave disabled for normal firmware.
#ifndef OTIS_FORCE_BOOT_FAIL_BEFORE_CLOCKS
#define OTIS_FORCE_BOOT_FAIL_BEFORE_CLOCKS 0
#endif

#ifndef OTIS_FORCE_BOOT_FAIL_BEFORE_CAPTURE
#define OTIS_FORCE_BOOT_FAIL_BEFORE_CAPTURE 0
#endif

#ifndef OTIS_FORCE_BOOT_FAIL_BEFORE_RUN_MODE
#define OTIS_FORCE_BOOT_FAIL_BEFORE_RUN_MODE 0
#endif

#if OTIS_TCXO_COUNTER_BACKEND != OTIS_TCXO_COUNTER_BACKEND_FC0_GPIN0 && \
    OTIS_TCXO_COUNTER_BACKEND != OTIS_TCXO_COUNTER_BACKEND_GPIO_IRQ && \
    OTIS_TCXO_COUNTER_BACKEND != OTIS_TCXO_COUNTER_BACKEND_PIO_LONG_GATE && \
    OTIS_TCXO_COUNTER_BACKEND != OTIS_TCXO_COUNTER_BACKEND_PPS_GATED_RATIO
#error "OTIS_TCXO_COUNTER_BACKEND must be FC0_GPIN0, GPIO_IRQ, PIO_LONG_GATE, or PPS_GATED_RATIO."
#endif

#if OTIS_CAPTURE_BACKEND != OTIS_CAPTURE_BACKEND_IRQ && \
    OTIS_CAPTURE_BACKEND != OTIS_CAPTURE_BACKEND_PIO_FIFO
#error "OTIS_CAPTURE_BACKEND must be OTIS_CAPTURE_BACKEND_IRQ or OTIS_CAPTURE_BACKEND_PIO_FIFO."
#endif

#if OTIS_TCXO_COUNTER_BACKEND == OTIS_TCXO_COUNTER_BACKEND_PPS_GATED_RATIO && \
    OTIS_CAPTURE_BACKEND != OTIS_CAPTURE_BACKEND_IRQ
#error "PPS_GATED_RATIO requires the GPIO IRQ backend for the independent D14 REF observer."
#endif

#if OTIS_SW1_BRINGUP_MODE != OTIS_SW1_MODE_SYNTHETIC_USB && \
    OTIS_SW1_BRINGUP_MODE != OTIS_SW1_MODE_GPIO_LOOPBACK && \
    OTIS_SW1_BRINGUP_MODE != OTIS_SW1_MODE_GPS_PPS && \
    OTIS_SW1_BRINGUP_MODE != OTIS_SW1_MODE_TCXO_OBSERVE && \
    OTIS_SW1_BRINGUP_MODE != OTIS_SW1_MODE_H1_OCXO_OBSERVE
#error "OTIS_SW1_BRINGUP_MODE must be one of the OTIS_SW1_MODE_* constants."
#endif

#if OTIS_DAC_AD5693R_I2C_ADDRESS != 0x4Cu && \
    OTIS_DAC_AD5693R_I2C_ADDRESS != 0x4Eu
#error "OTIS_DAC_AD5693R_I2C_ADDRESS must be 0x4C or 0x4E."
#endif

#if OTIS_ENV_SHT4X_I2C_ADDRESS != 0x44u && \
    OTIS_ENV_SHT4X_I2C_ADDRESS != 0x45u && \
    OTIS_ENV_SHT4X_I2C_ADDRESS != 0x46u
#error "OTIS_ENV_SHT4X_I2C_ADDRESS must be 0x44, 0x45, or 0x46."
#endif

#if OTIS_ENV_BMP280_I2C_ADDRESS != 0x76u && \
    OTIS_ENV_BMP280_I2C_ADDRESS != 0x77u
#error "OTIS_ENV_BMP280_I2C_ADDRESS must be 0x76 or 0x77."
#endif

#if OTIS_ENV_SAMPLE_PERIOD_MS < 100u
#error "OTIS_ENV_SAMPLE_PERIOD_MS must be at least 100 ms."
#endif

#if OTIS_PHASE4_TEMPERATURE_MAX_AGE_MS < OTIS_ENV_SAMPLE_PERIOD_MS
#error "OTIS_PHASE4_TEMPERATURE_MAX_AGE_MS must cover at least one sample period."
#endif

#if OTIS_PHASE4_OBSERVED_GATE_TOLERANCE_US > 1000000u
#error "OTIS_PHASE4_OBSERVED_GATE_TOLERANCE_US must not exceed one second."
#endif

#if OTIS_DAC_MIN_CODE > OTIS_DAC_MAX_CODE
#error "OTIS_DAC_MIN_CODE must be <= OTIS_DAC_MAX_CODE."
#endif

#if OTIS_DAC_MAX_CODE > 0xFFFFu
#error "OTIS_DAC_MAX_CODE must fit in 16 bits."
#endif

#if OTIS_ENABLE_DAC_AD5693R && \
    OTIS_SW1_BRINGUP_MODE != OTIS_SW1_MODE_H1_OCXO_OBSERVE
#error "AD5693R lab actuation is supported only in H1 OCXO observe mode."
#endif

#if OTIS_ENABLE_GNSS_RECEIVER && \
    OTIS_SW1_BRINGUP_MODE != OTIS_SW1_MODE_H1_OCXO_OBSERVE
#error "The GNSS metadata receiver is supported only in H1 OCXO observe mode."
#endif

#if OTIS_GNSS_UART_TX_ENABLED
#error "The bounded GNSS programme requires Nano TX to remain electrically silent."
#endif

#if OTIS_GNSS_UART_BAUD != 9600u
#error "The Stage 2 receiver profile is frozen at 9600 baud."
#endif

#if OTIS_GNSS_SERVICE_BYTE_BUDGET < 1u || \
    OTIS_GNSS_SERVICE_BYTE_BUDGET > 64u
#error "OTIS_GNSS_SERVICE_BYTE_BUDGET must be between 1 and 64 bytes."
#endif

#if OTIS_GNSS_METADATA_MAX_AGE_MS < 1000u || \
    OTIS_GNSS_METADATA_MAX_AGE_MS > 10000u
#error "OTIS_GNSS_METADATA_MAX_AGE_MS must be between 1 and 10 seconds."
#endif

#if OTIS_GNSS_RECONNECT_GAP_MS <= OTIS_GNSS_METADATA_MAX_AGE_MS
#error "GNSS reconnect gap must exceed the metadata freshness limit."
#endif

#if OTIS_ENABLE_H1_DAC_SWEEP && !OTIS_ENABLE_DAC_AD5693R
#error "The H1 DAC sweep requires the explicit AD5693R lab actuator profile."
#endif

#if OTIS_ENABLE_PSEUDO_PPS_GENERATOR && \
    OTIS_SW1_BRINGUP_MODE != OTIS_SW1_MODE_H1_OCXO_OBSERVE
#error "The pseudo-PPS generator is supported only by the H1 loopback test profile."
#endif

#if OTIS_ENABLE_PSEUDO_PPS_GENERATOR && \
    (OTIS_TCXO_COUNTER_BACKEND != OTIS_TCXO_COUNTER_BACKEND_PPS_GATED_RATIO || \
     OTIS_CAPTURE_BACKEND != OTIS_CAPTURE_BACKEND_IRQ || \
     OTIS_ENABLE_PPS_DUAL_OBSERVER || OTIS_ENABLE_DAC_AD5693R || \
     OTIS_ENABLE_H1_DAC_SWEEP || OTIS_ENABLE_PHASE4_OBSERVE_PREVIEW || \
     OTIS_ENABLE_ENV_SENSORS || OTIS_ENABLE_GNSS_RECEIVER)
#error "The pseudo-PPS generator requires the isolated PPS-gated loopback test profile."
#endif

#if OTIS_ENABLE_PSEUDO_PPS_GENERATOR != 0 && \
    OTIS_ENABLE_PSEUDO_PPS_GENERATOR != 1
#error "OTIS_ENABLE_PSEUDO_PPS_GENERATOR must be 0 or 1."
#endif

#if OTIS_H1_DAC_SWEEP_MAX_STEPS < 9u || OTIS_H1_DAC_SWEEP_MAX_STEPS > 32u
#error "OTIS_H1_DAC_SWEEP_MAX_STEPS must be between 9 and 32."
#endif

#if OTIS_H1_DAC_SWEEP_TINY_STEP_CODES < 1u
#error "OTIS_H1_DAC_SWEEP_TINY_STEP_CODES must be at least 1."
#endif

#if OTIS_H1_LONG_GATE_PERIOD_US < 1000000u || \
    OTIS_H1_LONG_GATE_PERIOD_US > 400000000u
#error "OTIS_H1_LONG_GATE_PERIOD_US must be between 1 s and 400 s."
#endif

#if OTIS_H1_DAC_SWEEP_SLOPE_DWELL_MS < 2u * (OTIS_H1_LONG_GATE_PERIOD_US / 1000u)
#error "OTIS_H1_DAC_SWEEP_SLOPE_DWELL_MS must allow at least two long gates per dwell."
#endif

#if OTIS_FC0_CONTROL_READY_CLEAN_WINDOWS < 1u
#error "OTIS_FC0_CONTROL_READY_CLEAN_WINDOWS must be at least 1."
#endif

#if OTIS_ENABLE_PHASE4_OBSERVE_PREVIEW != 0 && \
    OTIS_ENABLE_PHASE4_OBSERVE_PREVIEW != 1
#error "OTIS_ENABLE_PHASE4_OBSERVE_PREVIEW must be 0 or 1."
#endif

#if OTIS_ENABLE_CX317_I_ONLY_PREVIEW != 0 && \
    OTIS_ENABLE_CX317_I_ONLY_PREVIEW != 1
#error "OTIS_ENABLE_CX317_I_ONLY_PREVIEW must be 0 or 1."
#endif

#if OTIS_ENABLE_DUAL_CORE_PARTITION != 0 && \
    OTIS_ENABLE_DUAL_CORE_PARTITION != 1
#error "OTIS_ENABLE_DUAL_CORE_PARTITION must be 0 or 1."
#endif

#if OTIS_ENABLE_DUAL_CORE_PARTITION && !OTIS_ENABLE_CX317_I_ONLY_PREVIEW
#error "The dual-core partition requires the selected I-only preview/estimator."
#endif

#if OTIS_ENABLE_DUAL_CORE_PARTITION && OTIS_ENABLE_CX317_BOUNDED_ACTIVE && \
    OTIS_CX317_ACTIVE_CAMPAIGN != OTIS_CX317_ACTIVE_CAMPAIGN_STAGE7_A && \
    OTIS_CX317_ACTIVE_CAMPAIGN != OTIS_CX317_ACTIVE_CAMPAIGN_STAGE7_B && \
    OTIS_CX317_ACTIVE_CAMPAIGN != \
        OTIS_CX317_ACTIVE_CAMPAIGN_STAGE7_REHEARSAL
#error "Dual-core bounded authority is restricted to the exact Stage 7 profiles."
#endif

#if !OTIS_ENABLE_DUAL_CORE_PARTITION && OTIS_ENABLE_CX317_BOUNDED_ACTIVE && \
    (OTIS_CX317_ACTIVE_CAMPAIGN == OTIS_CX317_ACTIVE_CAMPAIGN_STAGE7_A || \
     OTIS_CX317_ACTIVE_CAMPAIGN == OTIS_CX317_ACTIVE_CAMPAIGN_STAGE7_B || \
     OTIS_CX317_ACTIVE_CAMPAIGN == \
         OTIS_CX317_ACTIVE_CAMPAIGN_STAGE7_REHEARSAL)
#error "Stage 7 bounded authority requires the dual-core partition."
#endif

#if OTIS_ENABLE_CX317_I_ONLY_PREVIEW && OTIS_ENABLE_PHASE4_OBSERVE_PREVIEW
#error "The CX317 selected preview and legacy Phase 4 preview are mutually exclusive."
#endif

#if OTIS_ENABLE_CX317_I_ONLY_PREVIEW && \
    (OTIS_TCXO_COUNTER_BACKEND != OTIS_TCXO_COUNTER_BACKEND_PPS_GATED_RATIO || \
     !OTIS_PPS_BOUNDARY_BACKEND_QUALIFIED || !OTIS_ENABLE_ENV_SENSORS)
#error "The CX317 preview requires the qualified PPS-gated backend and environment context."
#endif

#if OTIS_ENABLE_CX317_BOUNDED_ACTIVE != 0 && \
    OTIS_ENABLE_CX317_BOUNDED_ACTIVE != 1
#error "OTIS_ENABLE_CX317_BOUNDED_ACTIVE must be 0 or 1."
#endif

#if OTIS_ENABLE_CX317_BOUNDED_ACTIVE && \
    (!OTIS_ENABLE_CX317_I_ONLY_PREVIEW || !OTIS_ENABLE_GNSS_RECEIVER || \
     !OTIS_ENABLE_DAC_AD5693R || OTIS_ENABLE_H1_DAC_SWEEP || \
     !OTIS_ENABLE_ENV_SENSORS || !OTIS_PPS_BOUNDARY_BACKEND_QUALIFIED || \
     OTIS_TCXO_COUNTER_BACKEND != OTIS_TCXO_COUNTER_BACKEND_PPS_GATED_RATIO)
#error "Bounded active control requires the dedicated preview, RX-only GNSS, qualified count, environment, and nonsweep DAC topology."
#endif

#if OTIS_ENABLE_CX317_BOUNDED_ACTIVE && \
    (OTIS_DAC_MIN_CODE != 0xA800u || OTIS_DAC_MAX_CODE != 0xAB00u)
#error "Bounded active control requires the immutable A800..AB00 DAC range."
#endif

#if OTIS_ENABLE_CX317_BOUNDED_ACTIVE && \
    OTIS_CX317_ACTIVE_CAMPAIGN == OTIS_CX317_ACTIVE_CAMPAIGN_A && \
    (OTIS_CX317_ACTIVE_START_CODE != 0xA950u || \
     OTIS_CX317_ACTIVE_CORRECTION_LIMIT != 16u || \
     OTIS_CX317_ACTIVE_CUMULATIVE_LIMIT_CODES != 336u)
#error "Campaign A active parameters differ from the immutable programme envelope."
#endif

#if OTIS_ENABLE_CX317_BOUNDED_ACTIVE && \
    OTIS_CX317_ACTIVE_CAMPAIGN == OTIS_CX317_ACTIVE_CAMPAIGN_B && \
    (OTIS_CX317_ACTIVE_START_CODE != 0xA800u || \
     OTIS_CX317_ACTIVE_CORRECTION_LIMIT != 8u || \
     OTIS_CX317_ACTIVE_CUMULATIVE_LIMIT_CODES != 168u)
#error "Campaign B active parameters differ from the immutable programme envelope."
#endif

#if OTIS_ENABLE_CX317_BOUNDED_ACTIVE && \
    OTIS_CX317_ACTIVE_CAMPAIGN == OTIS_CX317_ACTIVE_CAMPAIGN_STAGE7_A && \
    (OTIS_CX317_ACTIVE_START_CODE != 0xA800u || \
     OTIS_CX317_ACTIVE_CORRECTION_LIMIT != 4u || \
     OTIS_CX317_ACTIVE_CUMULATIVE_LIMIT_CODES != 84u)
#error "Stage 7 Part A parameters differ from the immutable programme envelope."
#endif

#if OTIS_ENABLE_CX317_BOUNDED_ACTIVE && \
    OTIS_CX317_ACTIVE_CAMPAIGN == OTIS_CX317_ACTIVE_CAMPAIGN_STAGE7_B && \
    (OTIS_CX317_ACTIVE_START_CODE < 0xA800u || \
     OTIS_CX317_ACTIVE_START_CODE > 0xAB00u || \
     OTIS_CX317_ACTIVE_CORRECTION_LIMIT != 32u || \
     OTIS_CX317_ACTIVE_CUMULATIVE_LIMIT_CODES != 672u)
#error "Stage 7 Part B parameters differ from the immutable programme envelope."
#endif

#if OTIS_ENABLE_CX317_BOUNDED_ACTIVE && \
    OTIS_CX317_ACTIVE_CAMPAIGN == \
        OTIS_CX317_ACTIVE_CAMPAIGN_STAGE7_REHEARSAL && \
    (OTIS_CX317_ACTIVE_START_CODE != 0xA800u || \
     OTIS_CX317_ACTIVE_CORRECTION_LIMIT != 1u || \
     OTIS_CX317_ACTIVE_CUMULATIVE_LIMIT_CODES != 21u || \
     OTIS_CX317_SELECTED_SPAN_INTERVALS_CONFIG != 120u || \
     OTIS_CX317_STARTUP_WARMUP_S != 60u || \
     OTIS_CX317_SETTLING_EXCLUSION_S != 60u || \
     OTIS_CX317_FULL_HISTORY_RESET_S != 180u || \
     OTIS_CX317_RECOVERY_FRESH_SUPPORT_S != 120u || \
     OTIS_CX317_DECISION_CADENCE_S != 240u || \
     OTIS_CX317_MINIMUM_APPLIED_CADENCE_S != 240u)
#error "Stage 7 rehearsal parameters differ from the diagnostic-only contract."
#endif

#if OTIS_ENABLE_CX317_BOUNDED_ACTIVE && \
    OTIS_CX317_ACTIVE_CAMPAIGN != \
        OTIS_CX317_ACTIVE_CAMPAIGN_STAGE7_REHEARSAL && \
    (OTIS_CX317_SELECTED_SPAN_INTERVALS_CONFIG != 600u || \
     OTIS_CX317_STARTUP_WARMUP_S != 1800u || \
     OTIS_CX317_SETTLING_EXCLUSION_S != 900u || \
     OTIS_CX317_FULL_HISTORY_RESET_S != 1500u || \
     OTIS_CX317_RECOVERY_FRESH_SUPPORT_S != 600u || \
     OTIS_CX317_DECISION_CADENCE_S != 1800u || \
     OTIS_CX317_MINIMUM_APPLIED_CADENCE_S != 1800u)
#error "Qualification active timing differs from the frozen programme policy."
#endif

#if OTIS_ENABLE_CX317_BOUNDED_ACTIVE && \
    OTIS_CX317_ACTIVE_CAMPAIGN != OTIS_CX317_ACTIVE_CAMPAIGN_A && \
    OTIS_CX317_ACTIVE_CAMPAIGN != OTIS_CX317_ACTIVE_CAMPAIGN_B && \
    OTIS_CX317_ACTIVE_CAMPAIGN != OTIS_CX317_ACTIVE_CAMPAIGN_STAGE7_A && \
    OTIS_CX317_ACTIVE_CAMPAIGN != OTIS_CX317_ACTIVE_CAMPAIGN_STAGE7_B && \
    OTIS_CX317_ACTIVE_CAMPAIGN != \
        OTIS_CX317_ACTIVE_CAMPAIGN_STAGE7_REHEARSAL
#error "Bounded active control requires an exact programme campaign identity."
#endif

#if OTIS_PHASE4_PREVIEW_QUEUE_DEPTH < 2u || \
    OTIS_PHASE4_PREVIEW_QUEUE_DEPTH > 8u
#error "OTIS_PHASE4_PREVIEW_QUEUE_DEPTH must be between 2 and 8."
#endif

#if OTIS_PHASE4_ESTIMATOR_WINDOW < 3u || \
    OTIS_PHASE4_ESTIMATOR_WINDOW > 8u
#error "OTIS_PHASE4_ESTIMATOR_WINDOW must be between 3 and 8."
#endif

#if OTIS_PHASE4_MINIMUM_ESTIMATOR_SAMPLES < 1u || \
    OTIS_PHASE4_MINIMUM_ESTIMATOR_SAMPLES > OTIS_PHASE4_ESTIMATOR_WINDOW
#error "OTIS_PHASE4_MINIMUM_ESTIMATOR_SAMPLES must fit the estimator window."
#endif

#if OTIS_PHASE4_RECOVERY_CLEAN_WINDOWS < 1u
#error "OTIS_PHASE4_RECOVERY_CLEAN_WINDOWS must be at least 1."
#endif

#if OTIS_CAPTURE_RING_SIZE < 2u || OTIS_CAPTURE_RING_SIZE > 255u
#error "OTIS_CAPTURE_RING_SIZE must be between 2 and 255."
#endif

#if OTIS_PPS_COUNT_BOUNDARY_RING_SIZE < 3u || \
    OTIS_PPS_COUNT_BOUNDARY_RING_SIZE > 255u
#error "OTIS_PPS_COUNT_BOUNDARY_RING_SIZE must be between 3 and 255."
#endif

#if (OTIS_PPS_COUNT_BOUNDARY_RING_SIZE & \
     (OTIS_PPS_COUNT_BOUNDARY_RING_SIZE - 1u)) != 0u
#error "OTIS_PPS_COUNT_BOUNDARY_RING_SIZE must be a power of two."
#endif

#if OTIS_PPS_GATE_STATUS_PERIOD_MS < 1000u
#error "OTIS_PPS_GATE_STATUS_PERIOD_MS must be at least 1000 ms."
#endif

#if OTIS_PPS_BOUNDARY_BACKEND_QUALIFIED != 0 && \
    OTIS_PPS_BOUNDARY_BACKEND_QUALIFIED != 1
#error "OTIS_PPS_BOUNDARY_BACKEND_QUALIFIED must be 0 or 1."
#endif

#if OTIS_SAFE_MODE_FAILURE_THRESHOLD > 255u
#error "OTIS_SAFE_MODE_FAILURE_THRESHOLD must fit in uint8_t."
#endif

#if defined(ARDUINO)
#ifndef OTIS_BUILD_EXPECTED_OTIS_SW1_BRINGUP_MODE
#error "Generated profile is missing OTIS_SW1_BRINGUP_MODE."
#elif OTIS_SW1_BRINGUP_MODE != OTIS_BUILD_EXPECTED_OTIS_SW1_BRINGUP_MODE
#error "Effective OTIS_SW1_BRINGUP_MODE differs from the generated profile."
#endif
#ifndef OTIS_BUILD_EXPECTED_OTIS_CAPTURE_BACKEND
#error "Generated profile is missing OTIS_CAPTURE_BACKEND."
#elif OTIS_CAPTURE_BACKEND != OTIS_BUILD_EXPECTED_OTIS_CAPTURE_BACKEND
#error "Effective OTIS_CAPTURE_BACKEND differs from the generated profile."
#endif
#ifndef OTIS_BUILD_EXPECTED_OTIS_TCXO_COUNTER_BACKEND
#error "Generated profile is missing OTIS_TCXO_COUNTER_BACKEND."
#elif OTIS_TCXO_COUNTER_BACKEND != OTIS_BUILD_EXPECTED_OTIS_TCXO_COUNTER_BACKEND
#error "Effective OTIS_TCXO_COUNTER_BACKEND differs from the generated profile."
#endif
#ifndef OTIS_BUILD_EXPECTED_OTIS_ENABLE_PPS_DUAL_OBSERVER
#error "Generated profile is missing OTIS_ENABLE_PPS_DUAL_OBSERVER."
#elif OTIS_ENABLE_PPS_DUAL_OBSERVER != OTIS_BUILD_EXPECTED_OTIS_ENABLE_PPS_DUAL_OBSERVER
#error "Effective OTIS_ENABLE_PPS_DUAL_OBSERVER differs from the generated profile."
#endif
#ifndef OTIS_BUILD_EXPECTED_OTIS_ENABLE_PSEUDO_PPS_GENERATOR
#error "Generated profile is missing OTIS_ENABLE_PSEUDO_PPS_GENERATOR."
#elif OTIS_ENABLE_PSEUDO_PPS_GENERATOR != OTIS_BUILD_EXPECTED_OTIS_ENABLE_PSEUDO_PPS_GENERATOR
#error "Effective OTIS_ENABLE_PSEUDO_PPS_GENERATOR differs from the generated profile."
#endif
#ifndef OTIS_BUILD_EXPECTED_OTIS_PPS_BOUNDARY_BACKEND_QUALIFIED
#error "Generated profile is missing OTIS_PPS_BOUNDARY_BACKEND_QUALIFIED."
#elif OTIS_PPS_BOUNDARY_BACKEND_QUALIFIED != OTIS_BUILD_EXPECTED_OTIS_PPS_BOUNDARY_BACKEND_QUALIFIED
#error "Effective OTIS_PPS_BOUNDARY_BACKEND_QUALIFIED differs from the generated profile."
#endif
#ifndef OTIS_BUILD_EXPECTED_OTIS_PPS_GATE_MIN_INTERVAL_US
#error "Generated profile is missing OTIS_PPS_GATE_MIN_INTERVAL_US."
#elif OTIS_PPS_GATE_MIN_INTERVAL_US != OTIS_BUILD_EXPECTED_OTIS_PPS_GATE_MIN_INTERVAL_US
#error "Effective OTIS_PPS_GATE_MIN_INTERVAL_US differs from the generated profile."
#endif
#ifndef OTIS_BUILD_EXPECTED_OTIS_PPS_GATE_MAX_INTERVAL_US
#error "Generated profile is missing OTIS_PPS_GATE_MAX_INTERVAL_US."
#elif OTIS_PPS_GATE_MAX_INTERVAL_US != OTIS_BUILD_EXPECTED_OTIS_PPS_GATE_MAX_INTERVAL_US
#error "Effective OTIS_PPS_GATE_MAX_INTERVAL_US differs from the generated profile."
#endif
#ifndef OTIS_BUILD_EXPECTED_OTIS_ENABLE_PHASE4_OBSERVE_PREVIEW
#error "Generated profile is missing OTIS_ENABLE_PHASE4_OBSERVE_PREVIEW."
#elif OTIS_ENABLE_PHASE4_OBSERVE_PREVIEW != OTIS_BUILD_EXPECTED_OTIS_ENABLE_PHASE4_OBSERVE_PREVIEW
#error "Effective OTIS_ENABLE_PHASE4_OBSERVE_PREVIEW differs from the generated profile."
#endif
#ifdef OTIS_BUILD_EXPECTED_OTIS_ENABLE_CX317_I_ONLY_PREVIEW
#if OTIS_ENABLE_CX317_I_ONLY_PREVIEW != OTIS_BUILD_EXPECTED_OTIS_ENABLE_CX317_I_ONLY_PREVIEW
#error "Effective OTIS_ENABLE_CX317_I_ONLY_PREVIEW differs from the generated profile."
#endif
#ifdef OTIS_BUILD_EXPECTED_OTIS_ENABLE_DUAL_CORE_PARTITION
#if OTIS_ENABLE_DUAL_CORE_PARTITION != OTIS_BUILD_EXPECTED_OTIS_ENABLE_DUAL_CORE_PARTITION
#error "Effective OTIS_ENABLE_DUAL_CORE_PARTITION differs from the generated profile."
#endif
#endif
#ifdef OTIS_BUILD_EXPECTED_OTIS_ENABLE_CX317_BOUNDED_ACTIVE
#if OTIS_ENABLE_CX317_BOUNDED_ACTIVE != OTIS_BUILD_EXPECTED_OTIS_ENABLE_CX317_BOUNDED_ACTIVE
#error "Effective OTIS_ENABLE_CX317_BOUNDED_ACTIVE differs from the generated profile."
#endif
#endif
#ifdef OTIS_BUILD_EXPECTED_OTIS_CX317_ACTIVE_CAMPAIGN
#if OTIS_CX317_ACTIVE_CAMPAIGN != OTIS_BUILD_EXPECTED_OTIS_CX317_ACTIVE_CAMPAIGN
#error "Effective OTIS_CX317_ACTIVE_CAMPAIGN differs from the generated profile."
#endif
#endif
#ifdef OTIS_BUILD_EXPECTED_OTIS_CX317_ACTIVE_START_CODE
#if OTIS_CX317_ACTIVE_START_CODE != OTIS_BUILD_EXPECTED_OTIS_CX317_ACTIVE_START_CODE
#error "Effective OTIS_CX317_ACTIVE_START_CODE differs from the generated profile."
#endif
#endif
#ifdef OTIS_BUILD_EXPECTED_OTIS_CX317_ACTIVE_CORRECTION_LIMIT
#if OTIS_CX317_ACTIVE_CORRECTION_LIMIT != OTIS_BUILD_EXPECTED_OTIS_CX317_ACTIVE_CORRECTION_LIMIT
#error "Effective OTIS_CX317_ACTIVE_CORRECTION_LIMIT differs from the generated profile."
#endif
#endif
#ifdef OTIS_BUILD_EXPECTED_OTIS_CX317_ACTIVE_CUMULATIVE_LIMIT_CODES
#if OTIS_CX317_ACTIVE_CUMULATIVE_LIMIT_CODES != OTIS_BUILD_EXPECTED_OTIS_CX317_ACTIVE_CUMULATIVE_LIMIT_CODES
#error "Effective OTIS_CX317_ACTIVE_CUMULATIVE_LIMIT_CODES differs from the generated profile."
#endif
#endif
#ifdef OTIS_BUILD_EXPECTED_OTIS_CX317_SELECTED_SPAN_INTERVALS_CONFIG
#if OTIS_CX317_SELECTED_SPAN_INTERVALS_CONFIG != OTIS_BUILD_EXPECTED_OTIS_CX317_SELECTED_SPAN_INTERVALS_CONFIG
#error "Effective OTIS_CX317_SELECTED_SPAN_INTERVALS_CONFIG differs from the generated profile."
#endif
#endif
#ifdef OTIS_BUILD_EXPECTED_OTIS_CX317_STARTUP_WARMUP_S
#if OTIS_CX317_STARTUP_WARMUP_S != OTIS_BUILD_EXPECTED_OTIS_CX317_STARTUP_WARMUP_S
#error "Effective OTIS_CX317_STARTUP_WARMUP_S differs from the generated profile."
#endif
#endif
#ifdef OTIS_BUILD_EXPECTED_OTIS_CX317_SETTLING_EXCLUSION_S
#if OTIS_CX317_SETTLING_EXCLUSION_S != OTIS_BUILD_EXPECTED_OTIS_CX317_SETTLING_EXCLUSION_S
#error "Effective OTIS_CX317_SETTLING_EXCLUSION_S differs from the generated profile."
#endif
#endif
#ifdef OTIS_BUILD_EXPECTED_OTIS_CX317_FULL_HISTORY_RESET_S
#if OTIS_CX317_FULL_HISTORY_RESET_S != OTIS_BUILD_EXPECTED_OTIS_CX317_FULL_HISTORY_RESET_S
#error "Effective OTIS_CX317_FULL_HISTORY_RESET_S differs from the generated profile."
#endif
#endif
#ifdef OTIS_BUILD_EXPECTED_OTIS_CX317_RECOVERY_FRESH_SUPPORT_S
#if OTIS_CX317_RECOVERY_FRESH_SUPPORT_S != OTIS_BUILD_EXPECTED_OTIS_CX317_RECOVERY_FRESH_SUPPORT_S
#error "Effective OTIS_CX317_RECOVERY_FRESH_SUPPORT_S differs from the generated profile."
#endif
#endif
#ifdef OTIS_BUILD_EXPECTED_OTIS_CX317_DECISION_CADENCE_S
#if OTIS_CX317_DECISION_CADENCE_S != OTIS_BUILD_EXPECTED_OTIS_CX317_DECISION_CADENCE_S
#error "Effective OTIS_CX317_DECISION_CADENCE_S differs from the generated profile."
#endif
#endif
#ifdef OTIS_BUILD_EXPECTED_OTIS_CX317_MINIMUM_APPLIED_CADENCE_S
#if OTIS_CX317_MINIMUM_APPLIED_CADENCE_S != OTIS_BUILD_EXPECTED_OTIS_CX317_MINIMUM_APPLIED_CADENCE_S
#error "Effective OTIS_CX317_MINIMUM_APPLIED_CADENCE_S differs from the generated profile."
#endif
#endif
#endif
#ifdef OTIS_BUILD_EXPECTED_OTIS_ENABLE_GNSS_RECEIVER
#if OTIS_ENABLE_GNSS_RECEIVER != OTIS_BUILD_EXPECTED_OTIS_ENABLE_GNSS_RECEIVER
#error "Effective OTIS_ENABLE_GNSS_RECEIVER differs from the generated profile."
#endif
#endif
#ifdef OTIS_BUILD_EXPECTED_OTIS_GNSS_UART_TX_ENABLED
#if OTIS_GNSS_UART_TX_ENABLED != OTIS_BUILD_EXPECTED_OTIS_GNSS_UART_TX_ENABLED
#error "Effective OTIS_GNSS_UART_TX_ENABLED differs from the generated profile."
#endif
#endif
#ifndef OTIS_BUILD_EXPECTED_OTIS_ENABLE_DAC_AD5693R
#error "Generated profile is missing OTIS_ENABLE_DAC_AD5693R."
#elif OTIS_ENABLE_DAC_AD5693R != OTIS_BUILD_EXPECTED_OTIS_ENABLE_DAC_AD5693R
#error "Effective OTIS_ENABLE_DAC_AD5693R differs from the generated profile."
#endif
#ifdef OTIS_BUILD_EXPECTED_OTIS_DAC_MIN_CODE
#if OTIS_DAC_MIN_CODE != OTIS_BUILD_EXPECTED_OTIS_DAC_MIN_CODE
#error "Effective OTIS_DAC_MIN_CODE differs from the generated profile."
#endif
#endif
#ifdef OTIS_BUILD_EXPECTED_OTIS_DAC_MAX_CODE
#if OTIS_DAC_MAX_CODE != OTIS_BUILD_EXPECTED_OTIS_DAC_MAX_CODE
#error "Effective OTIS_DAC_MAX_CODE differs from the generated profile."
#endif
#endif
#ifndef OTIS_BUILD_EXPECTED_OTIS_ENABLE_H1_DAC_SWEEP
#error "Generated profile is missing OTIS_ENABLE_H1_DAC_SWEEP."
#elif OTIS_ENABLE_H1_DAC_SWEEP != OTIS_BUILD_EXPECTED_OTIS_ENABLE_H1_DAC_SWEEP
#error "Effective OTIS_ENABLE_H1_DAC_SWEEP differs from the generated profile."
#endif
#ifndef OTIS_BUILD_EXPECTED_OTIS_ENABLE_ENV_SENSORS
#error "Generated profile is missing OTIS_ENABLE_ENV_SENSORS."
#elif OTIS_ENABLE_ENV_SENSORS != OTIS_BUILD_EXPECTED_OTIS_ENABLE_ENV_SENSORS
#error "Effective OTIS_ENABLE_ENV_SENSORS differs from the generated profile."
#endif
#endif

#endif
