// Generated from data_contracts/otis_firmware_host_contract_v1.json.
// Do not edit by hand; run tools/generate_firmware_host_contract.py.
#ifndef OTIS_FIRMWARE_HOST_CONTRACT_GENERATED_H
#define OTIS_FIRMWARE_HOST_CONTRACT_GENERATED_H

#define OTIS_FIRMWARE_HOST_CONTRACT_ID "OTIS_FIRMWARE_HOST_CONTRACT_V1"
#define OTIS_FIRMWARE_HOST_CONTRACT_SHA256 "495b0adc02a0ebd3f2bf55ecc8bd3be0e62bfff29723f655c13128e3799bb4a9"

#define OTIS_CONTRACT_ACTIVE_HYBRID_DECISIONS_V2_HEADER "record_type,schema_version,hybrid_record_sequence,decision_sequence,decision_timestamp_ticks,time_domain,decision_timestamp_s,run_identity,build_identity,image_identity,capture_session,source_first_sequence,source_last_sequence,frequency_estimator_sha256,frequency_error_hz,accumulated_edge_error_counts,tight_state,phase_estimator_sha256,phase_epoch,phase_observation_sequence,relative_phase_cycles,phase_continuous,phase_current,phase_step_detected,phase_recorder_published,current_applied_code,dac_epoch,phase_applied_code,phase_dac_epoch,state_before,state_after,frequency_term_hz,phase_term_hz,combined_demand_hz,raw_combined_delta_codes,requested_delta_codes,requested_code,counterfactual_frequency_only_delta_codes,phase_materially_influenced,step_limited,range_clamped,cadence_limited,count_limited,cumulative_budget_limited,correction_count_before,cumulative_movement_before_codes,authority_state,request_sequence,acceptance_sequence,application_sequence,response_class,actual_applied_code,actual_dac_epoch,downstream_epoch_exact,reason,active_policy_sha256,response_policy_sha256,actionable"
#define OTIS_CONTRACT_ACTIVE_HYBRID_DECISIONS_V2_SCHEMA_VERSION 2u
#define OTIS_CONTRACT_ACTIVE_HYBRID_DECISIONS_V2_FIELD_COUNT 58u
#define OTIS_CONTRACT_ACTIVE_HYBRID_MAINTENANCE_V1_HEADER "record_type,schema_version,maintenance_record_sequence,event,event_timestamp_ticks,time_domain,run_identity,build_identity,image_identity,policy_id,active_policy_sha256,capture_session,source_first_sequence,source_last_sequence,frequency_estimator_sha256,phase_epoch,phase_observation_sequence,phase_valid,current_applied_code,current_dac_epoch,hybrid_record_sequence,decision_sequence,transaction_record_sequence,transaction_event,request_sequence,application_sequence,actual_applied_code,actual_dac_epoch,downstream_epoch_exact,maintenance_state_before,maintenance_state_after,frontier_relation,interval_sign,persistence_count_before,persistence_count_after,raw_fll_demand_picocodes,raw_pll_demand_picocodes,candidate_total_demand_picocodes,safe_cap_codes,requested_delta_codes,requested_code,committed_fll_debt_before_picocodes,committed_pll_debt_before_picocodes,committed_fll_debt_after_picocodes,committed_pll_debt_after_picocodes,request_pending_before,request_pending_after,response_pending_before,response_pending_after,metadata_hold_before,metadata_hold_after,requalification_window_count_before,requalification_window_count_after,requalification_d14_d8_observation_sequence,evidence_burst_sequence,evidence_burst_record_ordinal,evidence_burst_record_count,reason,actionable"
#define OTIS_CONTRACT_ACTIVE_HYBRID_MAINTENANCE_V1_SCHEMA_VERSION 1u
#define OTIS_CONTRACT_ACTIVE_HYBRID_MAINTENANCE_V1_FIELD_COUNT 59u
#define OTIS_CONTRACT_ACTIVE_TRANSACTIONS_V2_HEADER "record_type,schema_version,transaction_record_sequence,event,event_timestamp_ticks,time_domain,run_identity,build_identity,image_identity,session_id,authorization_sequence,nonce,request_sequence,decision_sequence,source_first_sequence,source_last_sequence,decision_timestamp_s,current_applied_code,requested_delta_codes,requested_code,correction_ordinal,cumulative_after_codes,pre_error_hz,accepted_code,accepted_timestamp_s,applied_code,application_sequence,application_timestamp_s,i2c_ok,clamped,ambiguous,dac_epoch,estimator_history_reset,correction_count,cumulative_movement_codes,post_error_hz,observed_response_hz,cumulative_response_hz,consecutive_indeterminate,active_state,response_class,reason,estimator_sha256,model_sha256,active_policy_sha256,response_policy_sha256,numerical_policy_sha256,actionable,evidence_state"
#define OTIS_CONTRACT_ACTIVE_TRANSACTIONS_V2_SCHEMA_VERSION 2u
#define OTIS_CONTRACT_ACTIVE_TRANSACTIONS_V2_FIELD_COUNT 49u
#define OTIS_CONTRACT_ASSOCIATION_LOSS_DECISIONS_V1_HEADER "record_type,schema_version,decision_sequence,reason,classification,decision_ticks,pending_reference_sequence,pending_reference_ticks,pending_age_ticks,boundary_depth,boundary_dropped_count,next_reference_present,next_reference_sequence,next_reference_ticks,snapshot_initialized,snapshot_running,snapshot_fault_latched,snapshot_fault_flags,snapshot_session,snapshot_producer_ordinal,snapshot_consumer_ordinal,snapshot_backlog_depth,snapshot_backlog_high_water,snapshot_overwrite_count,snapshot_continuity_loss_count,snapshot_pio_rxstall_count,snapshot_dma_error_count,snapshot_dma_stopped_count,core1_loop_sequence,core1_last_snapshot_session,core1_last_snapshot_sequence,core1_phase,core1_phase_enter_ticks,core1_last_progress_ticks"
#define OTIS_CONTRACT_ASSOCIATION_LOSS_DECISIONS_V1_SCHEMA_VERSION 1u
#define OTIS_CONTRACT_ASSOCIATION_LOSS_DECISIONS_V1_FIELD_COUNT 34u
#define OTIS_CONTRACT_CONTROL_PREVIEWS_V1_HEADER "record_type,schema_version,control_seq,decision_id,decision_timestamp_ticks,time_domain,est_input_ref,plant_model_ref,plant_model_id,plant_model_version,plant_model_hash,policy_version,config_hash,control_state,previous_control_state,state_transition,transition_reason_code,preview_eligibility,eligibility_reason_codes,diagnostic_health,model_applicability,model_reason_codes,current_dac_code,frequency_error_hz,hz_per_code,raw_delta_codes,limited_delta_codes,proposed_dac_code,step_limited,range_clamped,preview_available,preview_only,actuation_authorized,actionable,decision_reason_code"
#define OTIS_CONTRACT_CONTROL_PREVIEWS_V1_SCHEMA_VERSION 1u
#define OTIS_CONTRACT_CONTROL_PREVIEWS_V1_FIELD_COUNT 35u
#define OTIS_CONTRACT_COUNT_OBSERVATIONS_V1_HEADER "record_type,schema_version,count_seq,channel_id,gate_open_ticks,gate_close_ticks,gate_domain,counted_edges,source_edge,source_domain,flags"
#define OTIS_CONTRACT_COUNT_OBSERVATIONS_V1_SCHEMA_VERSION 1u
#define OTIS_CONTRACT_COUNT_OBSERVATIONS_V1_FIELD_COUNT 11u
#define OTIS_CONTRACT_DAC_STEPS_V1_HEADER "record_type,schema_version,seq,elapsed_ms,step_index,dac_code_requested,dac_code_applied,dac_code_clamped,dac_voltage_measured_v,ocxo_tune_voltage_measured_v,dwell_ms,event,flags"
#define OTIS_CONTRACT_DAC_STEPS_V1_SCHEMA_VERSION 1u
#define OTIS_CONTRACT_DAC_STEPS_V1_FIELD_COUNT 13u
#define OTIS_CONTRACT_ENVIRONMENT_V1_HEADER "record_type,schema_version,env_seq,timestamp_ticks,observation_domain,source,role,temperature_c,relative_humidity_pct,pressure_pa,flags"
#define OTIS_CONTRACT_ENVIRONMENT_V1_SCHEMA_VERSION 1u
#define OTIS_CONTRACT_ENVIRONMENT_V1_FIELD_COUNT 11u
#define OTIS_CONTRACT_ESTIMATES_V2_HEADER "record_type,schema_version,estimate_seq,estimate_id,estimator_timestamp_ticks,time_domain,source_count_seq,source_count_ref,source_reference_first_seq,source_reference_last_seq,source_status_refs,source_dac_ref,manifest_ref,estimator_version,config_hash,observation_validity,observation_reason_codes,reference_validity,reference_age_s,reference_continuity,count_validity,count_age_s,count_continuity,diagnostic_health,diagnostic_reason_codes,frequency_observation_hz,accepted_sample_count,estimator_confidence,frequency_estimate_hz,frequency_error_hz,dispersion_hz,uncertainty_status,uncertainty_reason_codes,count_quantization_standard_uncertainty_hz,counter_aperture_standard_uncertainty_hz,reference_standard_uncertainty_hz,calibration_standard_uncertainty_hz,model_standard_uncertainty_hz,combined_standard_uncertainty_hz,coverage_factor,expanded_uncertainty_hz,correlation_policy,uncertainty_model_ref,drift_enabled,drift_hz_per_s,preview_eligibility,eligibility_reason_codes"
#define OTIS_CONTRACT_ESTIMATES_V2_SCHEMA_VERSION 2u
#define OTIS_CONTRACT_ESTIMATES_V2_FIELD_COUNT 47u
#define OTIS_CONTRACT_FORWARDED_MONITOR_SNAPSHOTS_V1_HEADER "record_type,schema_version,session,reference_session,snapshot_sequence,cumulative_down_counter,reference_sequence,reference_timestamp_ticks,status,backend,channel_id"
#define OTIS_CONTRACT_FORWARDED_MONITOR_SNAPSHOTS_V1_SCHEMA_VERSION 1u
#define OTIS_CONTRACT_FORWARDED_MONITOR_SNAPSHOTS_V1_FIELD_COUNT 11u
#define OTIS_CONTRACT_HEALTH_V1_HEADER "record_type,schema_version,status_seq,timestamp_ticks,status_domain,component,status_key,status_value,severity,flags"
#define OTIS_CONTRACT_HEALTH_V1_SCHEMA_VERSION 1u
#define OTIS_CONTRACT_HEALTH_V1_FIELD_COUNT 10u
#define OTIS_CONTRACT_PHASE_ESTIMATOR_OUTPUTS_V1_HEADER "record_type,schema_version,phase_epoch,observation_sequence,source_relative_phase_observation,raw_relative_phase_cycles,raw_relative_phase_time_ns,filtered_relative_phase_cycles,estimated_frequency_error_hz,estimator_id,configuration_sha256,estimate_age_s,qualification_state,uncertainty_status,reason_codes"
#define OTIS_CONTRACT_PHASE_ESTIMATOR_OUTPUTS_V1_SCHEMA_VERSION 1u
#define OTIS_CONTRACT_PHASE_ESTIMATOR_OUTPUTS_V1_FIELD_COUNT 15u
#define OTIS_CONTRACT_PPS_SNAPSHOTS_V1_HEADER "record_type,schema_version,session,snapshot_sequence,cumulative_down_counter,reference_sequence,reference_timestamp_ticks,status,backend"
#define OTIS_CONTRACT_PPS_SNAPSHOTS_V1_SCHEMA_VERSION 1u
#define OTIS_CONTRACT_PPS_SNAPSHOTS_V1_FIELD_COUNT 9u
#define OTIS_CONTRACT_RAW_EVENTS_V1_HEADER "record_type,schema_version,event_seq,channel_id,edge,timestamp_ticks,capture_domain,flags"
#define OTIS_CONTRACT_RAW_EVENTS_V1_SCHEMA_VERSION 1u
#define OTIS_CONTRACT_RAW_EVENTS_V1_FIELD_COUNT 8u
#define OTIS_CONTRACT_RELATIVE_PHASE_OBSERVATIONS_V1_HEADER "record_type,schema_version,phase_epoch,observation_sequence,capture_session,opening_snapshot_sequence,closing_snapshot_sequence,opening_reference_sequence,closing_reference_sequence,dac_epoch,source_backend,source_file_sha256,method_id,configuration_sha256,interval_edges,edge_error_cycles,relative_phase_cycles,relative_phase_time_ns,qualification_state,observation_age_s,discontinuity_reason,calibrated_uncertainty_status"
#define OTIS_CONTRACT_RELATIVE_PHASE_OBSERVATIONS_V1_SCHEMA_VERSION 1u
#define OTIS_CONTRACT_RELATIVE_PHASE_OBSERVATIONS_V1_FIELD_COUNT 22u
#define OTIS_CONTRACT_TIGHT_DEADBAND_DECISIONS_V1_HEADER "record_type,schema_version,decision_sequence,estimate_id,decision_timestamp_ticks,time_domain,capture_session,dac_epoch,integer_edge_error_counts,absolute_edge_error_counts,state_before,state_after,entry_counter,release_counter,transition,frequency_controller_eligible,requalified,requalification_reason,three_count_band_inside,two_count_band_inside,policy_id,policy_sha256,actionable,actuation_authorized,authorization_consumed,reason_codes"
#define OTIS_CONTRACT_TIGHT_DEADBAND_DECISIONS_V1_SCHEMA_VERSION 1u
#define OTIS_CONTRACT_TIGHT_DEADBAND_DECISIONS_V1_FIELD_COUNT 26u

#define OTIS_ACTIVE_STATUS_CONTRACT_ID "adaptive_hybrid_active_status_snapshot_v1"
#define OTIS_ACTIVE_STATUS_COMPONENT "adaptive_hybrid"
#define OTIS_ACTIVE_STATUS_FIELD_COUNT 45u
#define OTIS_ACTIVE_STATUS_ENVELOPE_COUNT 3u
#define OTIS_ACTIVE_STATUS_BURST_COUNT 48u
#define OTIS_EVIDENCE_SELECTED_PREFIX_COUNT 3u
#define OTIS_EVIDENCE_SELECTED_SUFFIX_COUNT 1u
#define OTIS_EVIDENCE_REQUEST_DECISION_COUNT 3u
#define OTIS_EVIDENCE_RESPONSE_DECISION_COUNT 2u
#define OTIS_EVIDENCE_RESPONSE_COMPLETION_COUNT 2u
#define OTIS_EVIDENCE_FAIL_TRANSITION_COUNT 1u
#define OTIS_EVIDENCE_REQUEST_FRONTIER 7u
#define OTIS_EVIDENCE_RESPONSE_FRONTIER 8u
#define OTIS_EVIDENCE_METADATA_TRANSITION_COUNT 1u
#define OTIS_EVIDENCE_METADATA_RESPONSE_FRONTIER 9u
#define OTIS_EVIDENCE_REQUEST_FAIL_FRONTIER 8u
#define OTIS_EVIDENCE_QUEUE_DEPTH 16u
#define OTIS_ESTIMATE_TO_DECISION_MAXIMUM_LAG_TICKS 60000000ull
#define OTIS_TELEMETRY_NONACTIVE_TIMING_HEALTH_COUNT 80u
#define OTIS_TELEMETRY_MAXIMUM_CONCURRENT_COUNT 176u
#define OTIS_TELEMETRY_MAXIMUM_BOOT_COUNT 171u
#define OTIS_TELEMETRY_QUEUE_DEPTH 176u
#define OTIS_COMMAND_ACTIVE_ARM_PREFIX "ACTIVE ARM"
#define OTIS_COMMAND_ACTIVE_ARM_PREFIX_LENGTH 10u
#define OTIS_COMMAND_ACTIVE_ARM_ARGUMENT_COUNT 3u
#define OTIS_COMMAND_ACTIVE_EVIDENCE_PREFIX "ACTIVE EVIDENCE"
#define OTIS_COMMAND_ACTIVE_EVIDENCE_PREFIX_LENGTH 15u
#define OTIS_COMMAND_ACTIVE_EVIDENCE_ARGUMENT_COUNT 2u
#define OTIS_COMMAND_ACTIVE_LEASE_PREFIX "ACTIVE LEASE"
#define OTIS_COMMAND_ACTIVE_LEASE_PREFIX_LENGTH 12u
#define OTIS_COMMAND_ACTIVE_LEASE_ARGUMENT_COUNT 1u
#define OTIS_COMMAND_ACTIVE_SETUP_PREFIX "ACTIVE SETUP"
#define OTIS_COMMAND_ACTIVE_SETUP_PREFIX_LENGTH 12u
#define OTIS_COMMAND_ACTIVE_SETUP_ARGUMENT_COUNT 8u
#define OTIS_COMMAND_ACTIVE_SNAPSHOT_PREFIX "ACTIVE SNAPSHOT"
#define OTIS_COMMAND_ACTIVE_SNAPSHOT_PREFIX_LENGTH 15u
#define OTIS_COMMAND_ACTIVE_SNAPSHOT_ARGUMENT_COUNT 1u

#endif
