// Generated by tools/generate_reference_acceptance_policy.py.
#ifndef OTIS_REFERENCE_ACCEPTANCE_POLICY_GENERATED_H
#define OTIS_REFERENCE_ACCEPTANCE_POLICY_GENERATED_H
#include "otis_reference_acceptance.h"
#define OTIS_REFERENCE_ACCEPTANCE_POLICY_SHA256 "ccbac9f756a0ff2932a3f1c160c464af06eaaa1713d8bbc0ceba73762f80fad3"
constexpr OtisReferenceAcceptancePolicy OTIS_REFERENCE_ACCEPTANCE_POLICY = {1000000u, 1250u, 8u, 133000000u, 16u, 8u, 1200000u};
#endif
