// Generated by tools/generate_reference_acceptance_policy.py.
#ifndef OTIS_REFERENCE_ACCEPTANCE_POLICY_GENERATED_H
#define OTIS_REFERENCE_ACCEPTANCE_POLICY_GENERATED_H
#include "otis_reference_acceptance.h"
#define OTIS_REFERENCE_ACCEPTANCE_POLICY_SHA256 "6185c27a630b77925e21ebbd7a9b4ab029908f86ef02cbd4f56db796a3999a44"
constexpr OtisReferenceAcceptancePolicy OTIS_REFERENCE_ACCEPTANCE_POLICY = {1000000u, 1250u, 8u, 133000000u, 16u, 8u, 1200000u};
#endif
