#include "otis_pseudo_pps_schedule.h"

#include <string.h>

namespace {

constexpr OtisPseudoPpsProfile kProfiles[] = {
    {"CLEAN_NOMINAL", OTIS_PSEUDO_PPS_PROFILE_VERSION},
    {"ONE_SHORT", OTIS_PSEUDO_PPS_PROFILE_VERSION},
    {"ONE_LONG", OTIS_PSEUDO_PPS_PROFILE_VERSION},
    {"ONE_OMIT", OTIS_PSEUDO_PPS_PROFILE_VERSION},
    {"DOUBLE", OTIS_PSEUDO_PPS_PROFILE_VERSION},
    {"BOUNCE", OTIS_PSEUDO_PPS_PROFILE_VERSION},
    {"NARROW_GLITCH", OTIS_PSEUDO_PPS_PROFILE_VERSION},
    {"POSITIVE_PHASE_STEP", OTIS_PSEUDO_PPS_PROFILE_VERSION},
    {"NEGATIVE_PHASE_STEP", OTIS_PSEUDO_PPS_PROFILE_VERSION},
    {"SUSTAINED_POSITIVE_OFFSET", OTIS_PSEUDO_PPS_PROFILE_VERSION},
    {"SUSTAINED_NEGATIVE_OFFSET", OTIS_PSEUDO_PPS_PROFILE_VERSION},
    {"REPEATED_OMISSIONS", OTIS_PSEUDO_PPS_PROFILE_VERSION},
    {"MIXED_MALFORMED", OTIS_PSEUDO_PPS_PROFILE_VERSION},
    {"RETURN_CLEAN", OTIS_PSEUDO_PPS_PROFILE_VERSION},
    {"COMPOSITE", OTIS_PSEUDO_PPS_PROFILE_VERSION},
};

struct Builder {
  OtisPseudoPpsStep *steps;
  size_t capacity;
  size_t count;
  bool ok;
};

void append(Builder *builder, uint32_t delay_us, uint32_t width_us,
            const char *intended_class, bool emits_pulse = true) {
  if (!builder->ok || builder->count >= builder->capacity || delay_us == 0u ||
      (emits_pulse && width_us == 0u)) {
    builder->ok = false;
    return;
  }
  builder->steps[builder->count++] = {
      delay_us, width_us, intended_class, emits_pulse};
}

void clean(Builder *builder, size_t count) {
  for (size_t index = 0u; index < count; ++index) {
    append(builder, OTIS_PSEUDO_PPS_NOMINAL_INTERVAL_US,
           OTIS_PSEUDO_PPS_NOMINAL_WIDTH_US, "clean");
  }
}

void omit_then_recover(Builder *builder, const char *omit_class) {
  append(builder, OTIS_PSEUDO_PPS_NOMINAL_INTERVAL_US, 0u, omit_class, false);
  append(builder, OTIS_PSEUDO_PPS_NOMINAL_INTERVAL_US,
         OTIS_PSEUDO_PPS_NOMINAL_WIDTH_US, "recovery");
}

void double_pulse(Builder *builder) {
  // The short primary width leaves an unambiguous low interval before the
  // duplicate rising edge. Both edges are generated by the same PIO SM.
  append(builder, OTIS_PSEUDO_PPS_NOMINAL_INTERVAL_US, 10000u,
         "double_primary");
  append(builder, 50000u, OTIS_PSEUDO_PPS_NOMINAL_WIDTH_US,
         "double_secondary");
}

void bounce(Builder *builder) {
  append(builder, OTIS_PSEUDO_PPS_NOMINAL_INTERVAL_US, 100u,
         "bounce_primary");
  append(builder, 2000u, 100u, "bounce_secondary");
  append(builder, 2000u, 100u, "bounce_secondary");
  append(builder, 2000u, 100u, "bounce_secondary");
}

void mixed(Builder *builder) {
  append(builder, 750000u, OTIS_PSEUDO_PPS_NOMINAL_WIDTH_US,
         "short_interval");
  append(builder, 1250000u, OTIS_PSEUDO_PPS_NOMINAL_WIDTH_US,
         "long_interval");
  append(builder, OTIS_PSEUDO_PPS_NOMINAL_INTERVAL_US, 10u, "narrow_glitch");
  omit_then_recover(builder, "omission");
  double_pulse(builder);
}

}  // namespace

size_t otis_pseudo_pps_profile_count(void) {
  return sizeof(kProfiles) / sizeof(kProfiles[0]);
}

const OtisPseudoPpsProfile *otis_pseudo_pps_profile_at(size_t index) {
  return index < otis_pseudo_pps_profile_count() ? &kProfiles[index] : nullptr;
}

bool otis_pseudo_pps_compile_profile(const char *profile_id,
                                     OtisPseudoPpsStep *steps,
                                     size_t capacity,
                                     size_t *step_count) {
  if (profile_id == nullptr || steps == nullptr || step_count == nullptr) {
    return false;
  }
  *step_count = 0u;
  Builder builder = {steps, capacity, 0u, true};

  if (strcmp(profile_id, "CLEAN_NOMINAL") == 0) {
    clean(&builder, 30u);
  } else if (strcmp(profile_id, "ONE_SHORT") == 0) {
    clean(&builder, 3u);
    append(&builder, 750000u, OTIS_PSEUDO_PPS_NOMINAL_WIDTH_US,
           "short_interval");
    clean(&builder, 3u);
  } else if (strcmp(profile_id, "ONE_LONG") == 0) {
    clean(&builder, 3u);
    append(&builder, 1250000u, OTIS_PSEUDO_PPS_NOMINAL_WIDTH_US,
           "long_interval");
    clean(&builder, 3u);
  } else if (strcmp(profile_id, "ONE_OMIT") == 0) {
    clean(&builder, 3u);
    omit_then_recover(&builder, "omission");
    clean(&builder, 3u);
  } else if (strcmp(profile_id, "DOUBLE") == 0) {
    clean(&builder, 3u);
    double_pulse(&builder);
    clean(&builder, 3u);
  } else if (strcmp(profile_id, "BOUNCE") == 0) {
    clean(&builder, 3u);
    bounce(&builder);
    clean(&builder, 3u);
  } else if (strcmp(profile_id, "NARROW_GLITCH") == 0) {
    clean(&builder, 3u);
    append(&builder, OTIS_PSEUDO_PPS_NOMINAL_INTERVAL_US, 10u,
           "narrow_glitch");
    clean(&builder, 3u);
  } else if (strcmp(profile_id, "POSITIVE_PHASE_STEP") == 0) {
    clean(&builder, 3u);
    append(&builder, 1100000u, OTIS_PSEUDO_PPS_NOMINAL_WIDTH_US,
           "positive_phase_step");
    clean(&builder, 3u);
  } else if (strcmp(profile_id, "NEGATIVE_PHASE_STEP") == 0) {
    clean(&builder, 3u);
    append(&builder, 900000u, OTIS_PSEUDO_PPS_NOMINAL_WIDTH_US,
           "negative_phase_step_safe");
    clean(&builder, 3u);
  } else if (strcmp(profile_id, "SUSTAINED_POSITIVE_OFFSET") == 0) {
    for (size_t index = 0u; index < 8u; ++index) {
      append(&builder, 1001000u, OTIS_PSEUDO_PPS_NOMINAL_WIDTH_US,
             "sustained_positive_offset");
    }
  } else if (strcmp(profile_id, "SUSTAINED_NEGATIVE_OFFSET") == 0) {
    for (size_t index = 0u; index < 8u; ++index) {
      append(&builder, 999000u, OTIS_PSEUDO_PPS_NOMINAL_WIDTH_US,
             "sustained_negative_offset");
    }
  } else if (strcmp(profile_id, "REPEATED_OMISSIONS") == 0) {
    clean(&builder, 3u);
    append(&builder, OTIS_PSEUDO_PPS_NOMINAL_INTERVAL_US, 0u, "omission",
           false);
    append(&builder, OTIS_PSEUDO_PPS_NOMINAL_INTERVAL_US, 0u, "omission",
           false);
    append(&builder, OTIS_PSEUDO_PPS_NOMINAL_INTERVAL_US,
           OTIS_PSEUDO_PPS_NOMINAL_WIDTH_US, "recovery");
    clean(&builder, 3u);
  } else if (strcmp(profile_id, "MIXED_MALFORMED") == 0) {
    clean(&builder, 3u);
    mixed(&builder);
    clean(&builder, 3u);
  } else if (strcmp(profile_id, "RETURN_CLEAN") == 0) {
    clean(&builder, 30u);
  } else if (strcmp(profile_id, "COMPOSITE") == 0) {
    // Acceptance sequence: 30 clean; short; 10 clean; omission; recovery;
    // double; bounce; 30 clean.
    clean(&builder, 30u);
    append(&builder, 750000u, OTIS_PSEUDO_PPS_NOMINAL_WIDTH_US,
           "short_interval");
    clean(&builder, 10u);
    omit_then_recover(&builder, "omission");
    double_pulse(&builder);
    bounce(&builder);
    clean(&builder, 30u);
  } else {
    return false;
  }

  if (!builder.ok || builder.count == 0u) {
    return false;
  }
  *step_count = builder.count;
  return true;
}

bool otis_pseudo_pps_encode_schedule(const OtisPseudoPpsStep *steps,
                                     size_t step_count, uint32_t *words,
                                     size_t word_capacity,
                                     size_t *word_count) {
  if (steps == nullptr || words == nullptr || word_count == nullptr ||
      step_count == 0u || step_count > OTIS_PSEUDO_PPS_MAX_STEPS) {
    return false;
  }
  *word_count = 0u;
  uint64_t scheduled_offset_us = 0u;
  uint64_t previous_rise_us = 0u;
  uint32_t previous_width_us = 0u;
  bool first_pulse = true;

  for (size_t index = 0u; index < step_count; ++index) {
    const OtisPseudoPpsStep &step = steps[index];
    if (step.delay_us == 0u) {
      return false;
    }
    scheduled_offset_us += step.delay_us;
    if (scheduled_offset_us > UINT32_MAX || !step.emits_pulse) {
      continue;
    }
    if (step.pulse_width_us < 4u || *word_count + 2u >= word_capacity) {
      return false;
    }

    uint64_t interval_us = scheduled_offset_us - previous_rise_us;
    uint64_t low_loop_count = 0u;
    if (first_pulse) {
      // From SM enable through the first SET-high transition: eight PIO
      // instruction cycles plus X+1 low-loop cycles, represented as X=D-8.
      if (interval_us < 8u) {
        return false;
      }
      low_loop_count = interval_us - 8u;
    } else {
      // Rise-to-fall is Y+3 cycles. Fall-to-next-rise is X+7 cycles.
      if (interval_us < static_cast<uint64_t>(previous_width_us) + 7u) {
        return false;
      }
      low_loop_count =
          interval_us - static_cast<uint64_t>(previous_width_us) - 7u;
    }
    if (low_loop_count > UINT32_MAX) {
      return false;
    }

    words[(*word_count)++] = step.pulse_width_us - 3u;
    words[(*word_count)++] = static_cast<uint32_t>(low_loop_count);
    previous_rise_us = scheduled_offset_us;
    previous_width_us = step.pulse_width_us;
    first_pulse = false;
  }

  if (first_pulse || *word_count >= word_capacity) {
    return false;
  }
  words[(*word_count)++] = 0u;  // Completion sentinel, consumed while low.
  return true;
}
