// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

#define otis_pps_snapshot_wrap_target 0
#define otis_pps_snapshot_wrap 14
#define otis_pps_snapshot_pio_version 0
#define otis_pps_snapshot_initial_pc 11

static __pio_const uint16_t otis_pps_snapshot_program_instructions[] = {
    0x20a0,  //  0: wait 1 pin, 0
    0x0042,  //  1: jmp x--, 2
    0x00c6,  //  2: jmp pin, 6
    0x2020,  //  3: wait 0 pin, 0
    0x00ca,  //  4: jmp pin, 10
    0x0000,  //  5: jmp 0
    0x4020,  //  6: in x, 32
    0x2020,  //  7: wait 0 pin, 0
    0x00cb,  //  8: jmp pin, 11
    0x0000,  //  9: jmp 0
    0x4020,  // 10: in x, 32
    0x20a0,  // 11: wait 1 pin, 0
    0x004d,  // 12: jmp x--, 13
    0x00c7,  // 13: jmp pin, 7
    0x0003,  // 14: jmp 3
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program otis_pps_snapshot_program = {
    .instructions = otis_pps_snapshot_program_instructions,
    .length = 15,
    .origin = -1,
    .pio_version = otis_pps_snapshot_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config otis_pps_snapshot_program_get_default_config(
    uint offset) {
  pio_sm_config config = pio_get_default_sm_config();
  sm_config_set_wrap(&config, offset + otis_pps_snapshot_wrap_target,
                     offset + otis_pps_snapshot_wrap);
  return config;
}
#endif
