#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import argparse
import hashlib
import json
import sys

SCRIPT_REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
if str(SCRIPT_REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(SCRIPT_REPOSITORY_ROOT))

from host.otis_tools.plant_model import (
    REPOSITORY_ROOT,
    load_plant_model,
    validate_plant_model_semantics,
    validate_plant_model_structure,
)


DEFAULT_MODEL = (
    REPOSITORY_ROOT
    / "profiles"
    / "plant_models"
    / "cx317_h1_bench_v3.json"
)
DEFAULT_OUTPUT = (
    REPOSITORY_ROOT
    / "firmware"
    / "arduino"
    / "otis_nano_rp2040_connect"
    / "otis_plant_model_v4_generated.h"
)


def _c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def render_binding(model_path: Path) -> str:
    model_bytes = model_path.read_bytes()
    model = load_plant_model(model_path)
    structural = validate_plant_model_structure(model.data)
    semantic = validate_plant_model_semantics(model.data)
    if not structural.valid or not semantic.valid:
        # load_plant_model already rejects either state. Keep this assertion
        # local so the generated flags cannot silently diverge in the future.
        raise ValueError("refusing to bind an invalid plant model")

    try:
        model_ref = model_path.resolve().relative_to(REPOSITORY_ROOT).as_posix()
    except ValueError as exc:
        raise ValueError("plant model must be inside the repository") from exc
    applicability = model.data["plant_response"]["applicability"]
    estimator = applicability["estimator_method_contract"]
    applicable_range = applicability["dac_code_range"]
    candidate_range = model.data["dac"]["automatic_control_range_codes"]
    slope = model.data["plant_response"]["local_slope"]["hz_per_code"]
    if not isinstance(slope, (int, float)):
        raise ValueError("bound plant model requires a numeric hz_per_code")

    return f"""// Generated by tools/generate_plant_model_binding.py.
// Source: {model_ref}
// Do not edit by hand; regenerate only after validating the source artifact.
#ifndef OTIS_PLANT_MODEL_V4_GENERATED_H
#define OTIS_PLANT_MODEL_V4_GENERATED_H

#include <stdint.h>

constexpr char kPlantModelRef[] = {_c_string(model_ref)};
constexpr char kPlantModelId[] = {_c_string(model.model_id)};
constexpr char kPlantModelHash[] =
    {_c_string(hashlib.sha256(model_bytes).hexdigest())};
constexpr uint32_t kPlantModelSchemaVersion = {model.data["schema_version"]}u;
constexpr uint32_t kPlantModelVersion = {model.model_version}u;
constexpr bool kPlantModelStructurallyValid = true;
constexpr bool kPlantModelSemanticallyValid = true;
constexpr bool kPlantModelControlReady = {'true' if model.control_ready else 'false'};
constexpr bool kPlantModelActuationEnabled = {'true' if model.actuation_enabled else 'false'};
constexpr char kPlantModelEstimatorVersion[] =
    {_c_string(str(estimator["estimator_method_id"]))};
constexpr char kPlantModelEstimatorMethodHash[] =
    {_c_string(str(estimator["method_definition_hash"]))};
constexpr uint16_t kModelApplicabilityMin = 0x{applicable_range["min"]:04X}u;
constexpr uint16_t kModelApplicabilityMax = 0x{applicable_range["max"]:04X}u;
constexpr uint16_t kCandidateMin = 0x{candidate_range["min"]:04X}u;
constexpr uint16_t kCandidateMax = 0x{candidate_range["max"]:04X}u;
constexpr uint16_t kMaximumPreviewStep = 0x{model.data["dac"]["manual_preview_max_step_codes"]:04X}u;
constexpr double kHzPerCode = {slope};

#endif
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate the validated Phase-4 firmware plant-model binding."
    )
    parser.add_argument("--model", type=Path, default=DEFAULT_MODEL)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the committed generated header is stale",
    )
    args = parser.parse_args(argv)

    try:
        rendered = render_binding(args.model.resolve())
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        print(f"ERROR: {exc}")
        return 1

    if args.check:
        try:
            current = args.output.read_text(encoding="utf-8")
        except OSError as exc:
            print(f"ERROR: cannot read {args.output}: {exc}")
            return 1
        if current != rendered:
            print(
                f"ERROR: {args.output} is stale; regenerate from the validated "
                f"artifact {args.model}"
            )
            return 1
        print(f"OK: {args.output} matches validated artifact {args.model}")
        return 0

    args.output.write_text(rendered, encoding="utf-8")
    print(f"WROTE: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
