#!/usr/bin/env python3
"""Project the frozen reference-selection policy into the fixed firmware."""
from __future__ import annotations

import argparse
from hashlib import sha256
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
POLICY = ROOT / "data_contracts/reference_acceptance_policy_v2.json"
HEADER = ROOT / "firmware/arduino/otis_nano_rp2040_connect/otis_reference_acceptance_policy.generated.h"


def render_header() -> str:
    raw = POLICY.read_bytes()
    policy = json.loads(raw)
    fields = ("nominal_interval_ticks", "tolerance_ticks", "acquisition_intervals",
              "maximum_edge_rate_hz", "allowed_reference_flags",
              "maximum_excluded_candidates_per_span", "maximum_count_span_ticks")
    if any(type(policy.get(key)) is not int or not 0 <= policy[key] <= 0xffffffff for key in fields):
        raise ValueError("reference acceptance constants must be unsigned 32-bit integers")
    if (policy.get("schema_version") != 2
        or policy.get("policy_id") != "otis_d14_accepted_reference_v2"
        or policy["admission_coordinate_domain"] != "rp2040_monotonic_us32"
        or policy.get("admission_coordinate_semantics") != "fifo_cpu_service_coordinate"
        or policy.get("timestamp_uncertainty_field") != "timestamp_uncertainty_ticks"
        or policy.get("unknown_timestamp_uncertainty") != 0xFFFFFFFF
        or policy.get("reference_sequence_equals_snapshot_sequence") is not True
        or policy.get("qualification_requires_zero_snapshot_status") is not True
        or policy.get("interval_min_rule") != "service_delta_minus_closing_uncertainty"
        or policy.get("interval_max_rule") != "service_delta_plus_opening_uncertainty"
        or policy.get("early_exclusion_rule") != "interval_max_below_lower_bound"
        or policy.get("boundary_overlap_disposition") != "observation_age_ambiguous"
        or policy["reference_pin"] != "D14" or policy["count_pin"] != "D8"
        or policy["qualification_may_sum_acceptance_epochs"] is not False
        or policy["nominal_intervals_per_accepted_span"] != 1):
        raise ValueError("reference acceptance policy contradicts the fixed instrument")
    values = ", ".join(f"{policy[key]}u" for key in fields)
    return ("// Generated by tools/generate_reference_acceptance_policy.py.\n"
            "#ifndef OTIS_REFERENCE_ACCEPTANCE_POLICY_GENERATED_H\n"
            "#define OTIS_REFERENCE_ACCEPTANCE_POLICY_GENERATED_H\n"
            '#include "otis_reference_acceptance.h"\n'
            f'#define OTIS_REFERENCE_ACCEPTANCE_POLICY_SHA256 "{sha256(raw).hexdigest()}"\n'
            f"constexpr OtisReferenceAcceptancePolicy OTIS_REFERENCE_ACCEPTANCE_POLICY = {{{values}}};\n"
            "#endif\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render_header()
    if args.check:
        if HEADER.read_text() != expected:
            raise SystemExit("reference acceptance generated policy differs from its source")
    else:
        HEADER.write_text(expected)


if __name__ == "__main__":
    main()
